// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_LCC = NULL;
lv_obj_t * ui_RGBBox = NULL;
lv_obj_t * ui_RGB_Label = NULL;
lv_obj_t * ui_Group_Label = NULL;
lv_obj_t * ui_Lad = NULL;
lv_obj_t * ui_Lng = NULL;
lv_obj_t * ui_Exit_Btn = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Capture_Btn = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_RGB_Label(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        rgbchange(e);
    }
}

void ui_event_Exit_Btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_LCC_screen_init(void)
{
    ui_LCC = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LCC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_LCC, lv_color_hex(0x001359), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LCC, 156, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LCC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LCC, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RGBBox = lv_obj_create(ui_LCC);
    lv_obj_set_width(ui_RGBBox, 285);
    lv_obj_set_height(ui_RGBBox, 196);
    lv_obj_set_x(ui_RGBBox, -1);
    lv_obj_set_y(ui_RGBBox, -120);
    lv_obj_set_align(ui_RGBBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGBBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RGB_Label = lv_label_create(ui_LCC);
    lv_obj_set_width(ui_RGB_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RGB_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RGB_Label, 22);
    lv_obj_set_y(ui_RGB_Label, 7);
    lv_obj_set_align(ui_RGB_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_RGB_Label, "255 255 255");

    ui_Group_Label = lv_label_create(ui_LCC);
    lv_obj_set_width(ui_Group_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Group_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Group_Label, 253);
    lv_obj_set_y(ui_Group_Label, 10);
    lv_obj_set_align(ui_Group_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Group_Label, "1");

    ui_Lad = lv_label_create(ui_LCC);
    lv_obj_set_width(ui_Lad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lad, 26);
    lv_obj_set_y(ui_Lad, 76);
    lv_obj_set_align(ui_Lad, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lad, "0.00000000000");

    ui_Lng = lv_label_create(ui_LCC);
    lv_obj_set_width(ui_Lng, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lng, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lng, 27);
    lv_obj_set_y(ui_Lng, 114);
    lv_obj_set_align(ui_Lng, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lng, "0.00000000000");

    ui_Exit_Btn = lv_btn_create(ui_LCC);
    lv_obj_set_width(ui_Exit_Btn, 83);
    lv_obj_set_height(ui_Exit_Btn, 53);
    lv_obj_set_x(ui_Exit_Btn, 90);
    lv_obj_set_y(ui_Exit_Btn, 190);
    lv_obj_set_align(ui_Exit_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Exit_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Exit_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Exit_Btn, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Exit_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Exit_Btn);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "EXIT");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Capture_Btn = lv_btn_create(ui_LCC);
    lv_obj_set_width(ui_Capture_Btn, 83);
    lv_obj_set_height(ui_Capture_Btn, 53);
    lv_obj_set_x(ui_Capture_Btn, -50);
    lv_obj_set_y(ui_Capture_Btn, 189);
    lv_obj_set_align(ui_Capture_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Capture_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Capture_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Capture_Btn, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Capture_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Capture_Btn);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -1);
    lv_obj_set_y(ui_Label8, 1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Capture");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_RGB_Label, ui_event_RGB_Label, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Exit_Btn, ui_event_Exit_Btn, LV_EVENT_ALL, NULL);

}

void ui_LCC_screen_destroy(void)
{
    if(ui_LCC) lv_obj_del(ui_LCC);

    // NULL screen variables
    ui_LCC = NULL;
    ui_RGBBox = NULL;
    ui_RGB_Label = NULL;
    ui_Group_Label = NULL;
    ui_Lad = NULL;
    ui_Lng = NULL;
    ui_Exit_Btn = NULL;
    ui_Label7 = NULL;
    ui_Capture_Btn = NULL;
    ui_Label8 = NULL;

}
