// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LCC_H
#define UI_LCC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LCC
extern void ui_LCC_screen_init(void);
extern void ui_LCC_screen_destroy(void);
extern lv_obj_t * ui_LCC;
extern lv_obj_t * ui_RGBBox;
extern void ui_event_RGB_Label(lv_event_t * e);
extern lv_obj_t * ui_RGB_Label;
extern lv_obj_t * ui_Group_Label;
extern lv_obj_t * ui_Lad;
extern lv_obj_t * ui_Lng;
extern void ui_event_Exit_Btn(lv_event_t * e);
extern lv_obj_t * ui_Exit_Btn;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Capture_Btn;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

