// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LCC_Btn = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_LCC_image = NULL;
lv_obj_t * ui_GPS_Btn = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_GPS_image = NULL;
lv_obj_t * ui_SETTING_Btn = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_SETTING_image = NULL;
lv_obj_t * ui_WIFI_Btn = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_WIFI_image = NULL;
// event funtions
void ui_event_LCC_Btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_LCC, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_LCC_screen_init);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_Menu, lv_color_hex(0x001359), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Menu, 156, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Menu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Menu, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 29);
    lv_obj_set_y(ui_Label1, 47);
    lv_label_set_text(ui_Label1, "RICE COLOR LCC");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x38AF3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 33);
    lv_obj_set_y(ui_Label2, -138);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "v.0.0.1");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LCC_Btn = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_LCC_Btn, 120);
    lv_obj_set_height(ui_LCC_Btn, 120);
    lv_obj_set_x(ui_LCC_Btn, -76);
    lv_obj_set_y(ui_LCC_Btn, -46);
    lv_obj_set_align(ui_LCC_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LCC_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LCC_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LCC_Btn, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LCC_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_LCC_Btn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 36);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "LCC");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LCC_image = lv_img_create(ui_LCC_Btn);
    lv_obj_set_width(ui_LCC_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LCC_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LCC_image, 0);
    lv_obj_set_y(ui_LCC_image, -14);
    lv_obj_set_align(ui_LCC_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LCC_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_LCC_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GPS_Btn = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_GPS_Btn, 120);
    lv_obj_set_height(ui_GPS_Btn, 120);
    lv_obj_set_x(ui_GPS_Btn, 72);
    lv_obj_set_y(ui_GPS_Btn, -45);
    lv_obj_set_align(ui_GPS_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GPS_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GPS_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_GPS_Btn, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPS_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_GPS_Btn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, 36);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "GPS");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPS_image = lv_img_create(ui_GPS_Btn);
    lv_obj_set_width(ui_GPS_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPS_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GPS_image, 0);
    lv_obj_set_y(ui_GPS_image, -14);
    lv_obj_set_align(ui_GPS_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GPS_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_GPS_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SETTING_Btn = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_SETTING_Btn, 120);
    lv_obj_set_height(ui_SETTING_Btn, 120);
    lv_obj_set_x(ui_SETTING_Btn, 73);
    lv_obj_set_y(ui_SETTING_Btn, 124);
    lv_obj_set_align(ui_SETTING_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SETTING_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SETTING_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SETTING_Btn, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SETTING_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_SETTING_Btn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -1);
    lv_obj_set_y(ui_Label5, 36);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "SETTING");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SETTING_image = lv_img_create(ui_SETTING_Btn);
    lv_obj_set_width(ui_SETTING_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SETTING_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SETTING_image, 0);
    lv_obj_set_y(ui_SETTING_image, -14);
    lv_obj_set_align(ui_SETTING_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SETTING_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SETTING_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WIFI_Btn = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_WIFI_Btn, 120);
    lv_obj_set_height(ui_WIFI_Btn, 120);
    lv_obj_set_x(ui_WIFI_Btn, -76);
    lv_obj_set_y(ui_WIFI_Btn, 124);
    lv_obj_set_align(ui_WIFI_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFI_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WIFI_Btn, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFI_Btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_WIFI_Btn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, 36);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "WIFI");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFI_image = lv_img_create(ui_WIFI_Btn);
    lv_obj_set_width(ui_WIFI_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFI_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFI_image, 0);
    lv_obj_set_y(ui_WIFI_image, -14);
    lv_obj_set_align(ui_WIFI_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFI_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WIFI_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_LCC_Btn, ui_event_LCC_Btn, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    ui_Menu = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_LCC_Btn = NULL;
    ui_Label3 = NULL;
    ui_LCC_image = NULL;
    ui_GPS_Btn = NULL;
    ui_Label4 = NULL;
    ui_GPS_image = NULL;
    ui_SETTING_Btn = NULL;
    ui_Label5 = NULL;
    ui_SETTING_image = NULL;
    ui_WIFI_Btn = NULL;
    ui_Label6 = NULL;
    ui_WIFI_image = NULL;

}
