// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Menu.h"
#include "ui_Smart.h"
#include "ui_Garden.h"
#include "ui_Line.h"
#include "ui_Capture.h"
#include "ui_SelectWifi.h"
#include "ui_LoginWifi.h"
#include "ui_CreateGarden.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_marker_png);    // assets/marker.png
LV_IMG_DECLARE(ui_img_wifion_png);    // assets/WIFION.png
LV_IMG_DECLARE(ui_img_wifioff_png);    // assets/WIFIOFF.png
LV_IMG_DECLARE(ui_img_battery_png);    // assets/Battery.png
LV_IMG_DECLARE(ui_img_line_png);    // assets/line.png
LV_IMG_DECLARE(ui_img_159797012);    // assets/signal-alt-2.png
LV_IMG_DECLARE(ui_img_1039951338);    // assets/cloud-upload-alt.png
LV_IMG_DECLARE(ui_img_leave_png);    // assets/leave.png
LV_IMG_DECLARE(ui_img_nogps_png);    // assets/nogps.png
LV_IMG_DECLARE(ui_img_gps_png);    // assets/gps.png
LV_IMG_DECLARE(ui_img_qr_png);    // assets/qr.png
LV_IMG_DECLARE(ui_img_trash_png);    // assets/trash.png
LV_IMG_DECLARE(ui_img_lineqrcode_png);    // assets/lineqrcode.png
LV_IMG_DECLARE(ui_img_refresh_png);    // assets/refresh.png

// FONTS
LV_FONT_DECLARE(ui_font_SFPROEN_16);
LV_FONT_DECLARE(ui_font_SFPROEN_20);
LV_FONT_DECLARE(ui_font_SFPROEN_32);
LV_FONT_DECLARE(ui_font_SFPROTH_16);
LV_FONT_DECLARE(ui_font_SFPROTH_20);
LV_FONT_DECLARE(ui_font_SFPROTH_32);
LV_FONT_DECLARE(ui_font_THNEW_24);
LV_FONT_DECLARE(ui_font_THNEW_32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
