// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_CreateGarden = NULL;
lv_obj_t * ui_GardenTopBar1 = NULL;
lv_obj_t * ui_GardenText1 = NULL;
lv_obj_t * ui_ContainerGarden = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_GardenPointNum = NULL;
lv_obj_t * ui_SaveGarden_Btn = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_ContainerGardenname = NULL;
lv_obj_t * ui_GardenNameTextArea = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_KeyboardGardenName = NULL;
// event funtions

// build funtions

void ui_CreateGarden_screen_init(void)
{
    ui_CreateGarden = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CreateGarden, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenTopBar1 = lv_obj_create(ui_CreateGarden);
    lv_obj_set_width(ui_GardenTopBar1, 240);
    lv_obj_set_height(ui_GardenTopBar1, 49);
    lv_obj_set_x(ui_GardenTopBar1, 0);
    lv_obj_set_y(ui_GardenTopBar1, -136);
    lv_obj_set_align(ui_GardenTopBar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GardenTopBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenTopBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenTopBar1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenTopBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GardenTopBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenText1 = lv_label_create(ui_GardenTopBar1);
    lv_obj_set_width(ui_GardenText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GardenText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenText1, "Create Garden");
    lv_obj_set_style_text_font(ui_GardenText1, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerGarden = lv_obj_create(ui_CreateGarden);
    lv_obj_remove_style_all(ui_ContainerGarden);
    lv_obj_set_width(ui_ContainerGarden, 240);
    lv_obj_set_height(ui_ContainerGarden, 320);
    lv_obj_set_align(ui_ContainerGarden, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerGarden, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_ContainerGarden);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 1);
    lv_obj_set_y(ui_Label24, -60);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24,
                      "กรุณาไปที่มุมแต่และมุมของแปลง\nเพื่อทำการบันทึก");
    lv_obj_set_style_text_align(ui_Label24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_THNEW_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_ContainerGarden);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, -21);
    lv_obj_set_y(ui_Label25, 15);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "จุดที่");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_SFPROTH_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenPointNum = lv_label_create(ui_ContainerGarden);
    lv_obj_set_width(ui_GardenPointNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenPointNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GardenPointNum, 35);
    lv_obj_set_y(ui_GardenPointNum, 14);
    lv_obj_set_align(ui_GardenPointNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenPointNum, "1");
    lv_obj_set_style_text_font(ui_GardenPointNum, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveGarden_Btn = lv_btn_create(ui_ContainerGarden);
    lv_obj_set_width(ui_SaveGarden_Btn, 129);
    lv_obj_set_height(ui_SaveGarden_Btn, 50);
    lv_obj_set_x(ui_SaveGarden_Btn, 0);
    lv_obj_set_y(ui_SaveGarden_Btn, 111);
    lv_obj_set_align(ui_SaveGarden_Btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveGarden_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveGarden_Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_SaveGarden_Btn);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "ยืนยัน");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_SFPROTH_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerGardenname = lv_obj_create(ui_CreateGarden);
    lv_obj_remove_style_all(ui_ContainerGardenname);
    lv_obj_set_width(ui_ContainerGardenname, 240);
    lv_obj_set_height(ui_ContainerGardenname, 320);
    lv_obj_set_align(ui_ContainerGardenname, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerGardenname, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerGardenname, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenNameTextArea = lv_textarea_create(ui_ContainerGardenname);
    lv_obj_set_width(ui_GardenNameTextArea, 216);
    lv_obj_set_height(ui_GardenNameTextArea, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_GardenNameTextArea, 0);
    lv_obj_set_y(ui_GardenNameTextArea, -30);
    lv_obj_set_align(ui_GardenNameTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_GardenNameTextArea, 32);
    lv_textarea_set_placeholder_text(ui_GardenNameTextArea, "ชื่อสวน");
    lv_textarea_set_one_line(ui_GardenNameTextArea, true);

    lv_obj_set_style_text_font(ui_GardenNameTextArea, &ui_font_SFPROTH_20, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_ContainerGardenname);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -1);
    lv_obj_set_y(ui_Label27, -84);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "โปรดตั้งชื่อสวน");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardGardenName = lv_keyboard_create(ui_ContainerGardenname);
    lv_obj_set_width(ui_KeyboardGardenName, 240);
    lv_obj_set_height(ui_KeyboardGardenName, 146);
    lv_obj_set_x(ui_KeyboardGardenName, 0);
    lv_obj_set_y(ui_KeyboardGardenName, 86);
    lv_obj_set_align(ui_KeyboardGardenName, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_KeyboardGardenName, ui_GardenNameTextArea);

}

void ui_CreateGarden_screen_destroy(void)
{
    if(ui_CreateGarden) lv_obj_del(ui_CreateGarden);

    // NULL screen variables
    ui_CreateGarden = NULL;
    ui_GardenTopBar1 = NULL;
    ui_GardenText1 = NULL;
    ui_ContainerGarden = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_GardenPointNum = NULL;
    ui_SaveGarden_Btn = NULL;
    ui_Label26 = NULL;
    ui_ContainerGardenname = NULL;
    ui_GardenNameTextArea = NULL;
    ui_Label27 = NULL;
    ui_KeyboardGardenName = NULL;

}
