// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Capture = NULL;
lv_obj_t * ui_text = NULL;
lv_obj_t * ui_ColorBox = NULL;
lv_obj_t * ui_CaptureBar = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_SmartText1 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_tillerText = NULL;
lv_obj_t * ui_panicleText = NULL;
lv_obj_t * ui_panicleText1 = NULL;
lv_obj_t * ui_panicleText2 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_GroupValue = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_RValue = NULL;
lv_obj_t * ui_GValue = NULL;
lv_obj_t * ui_BValue = NULL;
lv_obj_t * ui_CaptureButton = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_SaveButton = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_CapturePanel = NULL;
lv_obj_t * ui_CaptureStatusText = NULL;
lv_obj_t * ui_Latvalue = NULL;
lv_obj_t * ui_Lngvalue = NULL;
lv_obj_t * ui_Capturecontain = NULL;
lv_obj_t * ui_CaptureBlurPanel1 = NULL;
lv_obj_t * ui_CapturePanel1 = NULL;
lv_obj_t * ui_CaptureStatusText1 = NULL;
lv_obj_t * ui_CaptureCloseBtn = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Savecontain = NULL;
lv_obj_t * ui_CaptureBlurPanel2 = NULL;
lv_obj_t * ui_CapturePanel2 = NULL;
lv_obj_t * ui_CaptureStatusText2 = NULL;
// event funtions
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

void ui_event_Label16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

void ui_event_CaptureCloseBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Capturecontain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Capture_screen_init(void)
{
    ui_Capture = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Capture, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_text = lv_label_create(ui_Capture);
    lv_obj_set_width(ui_text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_text, 42);
    lv_obj_set_y(ui_text, -97);
    lv_obj_set_align(ui_text, LV_ALIGN_CENTER);
    lv_label_set_text(ui_text, "พิกัด");
    lv_obj_set_style_text_font(ui_text, &ui_font_THNEW_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ColorBox = lv_obj_create(ui_Capture);
    lv_obj_set_width(ui_ColorBox, 133);
    lv_obj_set_height(ui_ColorBox, 100);
    lv_obj_set_x(ui_ColorBox, -47);
    lv_obj_set_y(ui_ColorBox, -59);
    lv_obj_set_align(ui_ColorBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ColorBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ColorBox, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ColorBox, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ColorBox, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureBar = lv_obj_create(ui_Capture);
    lv_obj_set_width(ui_CaptureBar, 240);
    lv_obj_set_height(ui_CaptureBar, 49);
    lv_obj_set_x(ui_CaptureBar, 0);
    lv_obj_set_y(ui_CaptureBar, -136);
    lv_obj_set_align(ui_CaptureBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CaptureBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureBar, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CaptureBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_CaptureBar);
    lv_obj_set_width(ui_Button7, 29);
    lv_obj_set_height(ui_Button7, 33);
    lv_obj_set_x(ui_Button7, -94);
    lv_obj_set_y(ui_Button7, 0);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button7, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "<");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_SFPROEN_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartText1 = lv_label_create(ui_CaptureBar);
    lv_obj_set_width(ui_SmartText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartText1, -35);
    lv_obj_set_y(ui_SmartText1, 2);
    lv_obj_set_align(ui_SmartText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartText1, "เก็บค่าสี");
    lv_obj_set_style_text_font(ui_SmartText1, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Capture);
    lv_obj_set_width(ui_Panel6, 222);
    lv_obj_set_height(ui_Panel6, 116);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 53);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -60);
    lv_obj_set_y(ui_Label17, -19);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "ระยะแตกกอ");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -37);
    lv_obj_set_y(ui_Label18, 6);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "ระยะสร้างรวงอ่อน");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -68);
    lv_obj_set_y(ui_Label19, -44);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "ปริมาณปุ๋ย");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tillerText = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_tillerText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tillerText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tillerText, 126);
    lv_obj_set_y(ui_tillerText, -17);
    lv_obj_set_align(ui_tillerText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_tillerText, "10.0");
    lv_obj_set_style_text_font(ui_tillerText, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panicleText = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_panicleText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_panicleText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_panicleText, 126);
    lv_obj_set_y(ui_panicleText, 9);
    lv_obj_set_align(ui_panicleText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_panicleText, "10.0");
    lv_obj_set_style_text_font(ui_panicleText, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panicleText1 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_panicleText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_panicleText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_panicleText1, 166);
    lv_obj_set_y(ui_panicleText1, 7);
    lv_obj_set_align(ui_panicleText1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_panicleText1, "กกไร่");
    lv_obj_set_style_text_font(ui_panicleText1, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panicleText2 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_panicleText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_panicleText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_panicleText2, 166);
    lv_obj_set_y(ui_panicleText2, -20);
    lv_obj_set_align(ui_panicleText2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_panicleText2, "กกไร่");
    lv_obj_set_style_text_font(ui_panicleText2, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -83);
    lv_obj_set_y(ui_Label21, 40);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "กลุ่มที่");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroupValue = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_GroupValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GroupValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GroupValue, -46);
    lv_obj_set_y(ui_GroupValue, 41);
    lv_obj_set_align(ui_GroupValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GroupValue, "1");
    lv_obj_set_style_text_font(ui_GroupValue, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 116);
    lv_obj_set_y(ui_Label22, 41);
    lv_obj_set_align(ui_Label22, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label22, "   ,         , ");

    ui_RValue = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_RValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RValue, 11);
    lv_obj_set_y(ui_RValue, 42);
    lv_obj_set_align(ui_RValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RValue, "255");
    lv_obj_set_style_text_font(ui_RValue, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GValue = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_GValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GValue, 49);
    lv_obj_set_y(ui_GValue, 42);
    lv_obj_set_align(ui_GValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GValue, "255");
    lv_obj_set_style_text_font(ui_GValue, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BValue = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_BValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BValue, 93);
    lv_obj_set_y(ui_BValue, 42);
    lv_obj_set_align(ui_BValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BValue, "255");
    lv_obj_set_style_text_font(ui_BValue, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureButton = lv_btn_create(ui_Capture);
    lv_obj_set_width(ui_CaptureButton, 102);
    lv_obj_set_height(ui_CaptureButton, 36);
    lv_obj_set_x(ui_CaptureButton, -59);
    lv_obj_set_y(ui_CaptureButton, 136);
    lv_obj_set_align(ui_CaptureButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CaptureButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CaptureButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureButton, lv_color_hex(0x88690B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CaptureButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_CaptureButton);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "เก็บค่า");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveButton = lv_btn_create(ui_Capture);
    lv_obj_set_width(ui_SaveButton, 102);
    lv_obj_set_height(ui_SaveButton, 36);
    lv_obj_set_x(ui_SaveButton, 59);
    lv_obj_set_y(ui_SaveButton, 136);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SaveButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SaveButton, lv_color_hex(0x196500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SaveButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_SaveButton);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "บันทึก");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CapturePanel = lv_obj_create(ui_Capture);
    lv_obj_set_width(ui_CapturePanel, 221);
    lv_obj_set_height(ui_CapturePanel, 147);
    lv_obj_set_align(ui_CapturePanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CapturePanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_CapturePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CapturePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CapturePanel, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CapturePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CapturePanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureStatusText = lv_label_create(ui_CapturePanel);
    lv_obj_set_width(ui_CaptureStatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CaptureStatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CaptureStatusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaptureStatusText, "บันทึกสำเร็จ");
    lv_obj_set_style_text_font(ui_CaptureStatusText, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Latvalue = lv_label_create(ui_Capture);
    lv_obj_set_width(ui_Latvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Latvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Latvalue, 148);
    lv_obj_set_y(ui_Latvalue, -76);
    lv_obj_set_align(ui_Latvalue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Latvalue, "100.000000");
    lv_obj_set_style_text_font(ui_Latvalue, &ui_font_THNEW_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lngvalue = lv_label_create(ui_Capture);
    lv_obj_set_width(ui_Lngvalue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lngvalue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lngvalue, 148);
    lv_obj_set_y(ui_Lngvalue, -51);
    lv_obj_set_align(ui_Lngvalue, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Lngvalue, "100.000000");
    lv_obj_set_style_text_font(ui_Lngvalue, &ui_font_THNEW_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Capturecontain = lv_obj_create(ui_Capture);
    lv_obj_remove_style_all(ui_Capturecontain);
    lv_obj_set_width(ui_Capturecontain, 240);
    lv_obj_set_height(ui_Capturecontain, 320);
    lv_obj_set_align(ui_Capturecontain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Capturecontain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Capturecontain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CaptureBlurPanel1 = lv_obj_create(ui_Capturecontain);
    lv_obj_set_width(ui_CaptureBlurPanel1, 240);
    lv_obj_set_height(ui_CaptureBlurPanel1, 320);
    lv_obj_set_align(ui_CaptureBlurPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CaptureBlurPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureBlurPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureBlurPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureBlurPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CaptureBlurPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_CaptureBlurPanel1, 1500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CapturePanel1 = lv_obj_create(ui_Capturecontain);
    lv_obj_set_width(ui_CapturePanel1, 221);
    lv_obj_set_height(ui_CapturePanel1, 147);
    lv_obj_set_align(ui_CapturePanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CapturePanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CapturePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CapturePanel1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CapturePanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CapturePanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureStatusText1 = lv_label_create(ui_CapturePanel1);
    lv_obj_set_width(ui_CaptureStatusText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CaptureStatusText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CaptureStatusText1, 0);
    lv_obj_set_y(ui_CaptureStatusText1, -22);
    lv_obj_set_align(ui_CaptureStatusText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaptureStatusText1, "ไม่มีสัญญาณ GPS");
    lv_obj_set_style_text_font(ui_CaptureStatusText1, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureCloseBtn = lv_btn_create(ui_Capturecontain);
    lv_obj_set_width(ui_CaptureCloseBtn, 100);
    lv_obj_set_height(ui_CaptureCloseBtn, 39);
    lv_obj_set_x(ui_CaptureCloseBtn, 0);
    lv_obj_set_y(ui_CaptureCloseBtn, 41);
    lv_obj_set_align(ui_CaptureCloseBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CaptureCloseBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CaptureCloseBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureCloseBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureCloseBtn, lv_color_hex(0xB50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureCloseBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_CaptureCloseBtn);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label28, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label28, "รับทราบ");
    lv_obj_set_style_text_font(ui_Label28, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Savecontain = lv_obj_create(ui_Capture);
    lv_obj_remove_style_all(ui_Savecontain);
    lv_obj_set_width(ui_Savecontain, 240);
    lv_obj_set_height(ui_Savecontain, 320);
    lv_obj_set_align(ui_Savecontain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Savecontain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Savecontain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CaptureBlurPanel2 = lv_obj_create(ui_Savecontain);
    lv_obj_set_width(ui_CaptureBlurPanel2, 240);
    lv_obj_set_height(ui_CaptureBlurPanel2, 320);
    lv_obj_set_align(ui_CaptureBlurPanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CaptureBlurPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureBlurPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureBlurPanel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureBlurPanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CaptureBlurPanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_CaptureBlurPanel2, 1500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CapturePanel2 = lv_obj_create(ui_Savecontain);
    lv_obj_set_width(ui_CapturePanel2, 221);
    lv_obj_set_height(ui_CapturePanel2, 147);
    lv_obj_set_align(ui_CapturePanel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CapturePanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CapturePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CapturePanel2, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CapturePanel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CapturePanel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureStatusText2 = lv_label_create(ui_CapturePanel2);
    lv_obj_set_width(ui_CaptureStatusText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CaptureStatusText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CaptureStatusText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaptureStatusText2, "บันทึกสำเร็จ");
    lv_obj_set_style_text_font(ui_CaptureStatusText2, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Label16, ui_event_Label16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CaptureCloseBtn, ui_event_CaptureCloseBtn, LV_EVENT_ALL, NULL);

}

void ui_Capture_screen_destroy(void)
{
    if(ui_Capture) lv_obj_del(ui_Capture);

    // NULL screen variables
    ui_Capture = NULL;
    ui_text = NULL;
    ui_ColorBox = NULL;
    ui_CaptureBar = NULL;
    ui_Button7 = NULL;
    ui_Label16 = NULL;
    ui_SmartText1 = NULL;
    ui_Panel6 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;
    ui_Label19 = NULL;
    ui_tillerText = NULL;
    ui_panicleText = NULL;
    ui_panicleText1 = NULL;
    ui_panicleText2 = NULL;
    ui_Label21 = NULL;
    ui_GroupValue = NULL;
    ui_Label22 = NULL;
    ui_RValue = NULL;
    ui_GValue = NULL;
    ui_BValue = NULL;
    ui_CaptureButton = NULL;
    ui_Label20 = NULL;
    ui_SaveButton = NULL;
    ui_Label23 = NULL;
    ui_CapturePanel = NULL;
    ui_CaptureStatusText = NULL;
    ui_Latvalue = NULL;
    ui_Lngvalue = NULL;
    ui_Capturecontain = NULL;
    ui_CaptureBlurPanel1 = NULL;
    ui_CapturePanel1 = NULL;
    ui_CaptureStatusText1 = NULL;
    ui_CaptureCloseBtn = NULL;
    ui_Label28 = NULL;
    ui_Savecontain = NULL;
    ui_CaptureBlurPanel2 = NULL;
    ui_CapturePanel2 = NULL;
    ui_CaptureStatusText2 = NULL;

}
