// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CREATEGARDEN_H
#define UI_CREATEGARDEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CreateGarden
extern void ui_CreateGarden_screen_init(void);
extern void ui_CreateGarden_screen_destroy(void);
extern lv_obj_t * ui_CreateGarden;
extern lv_obj_t * ui_GardenTopBar1;
extern lv_obj_t * ui_GardenText1;
extern lv_obj_t * ui_ContainerGarden;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_GardenPointNum;
extern lv_obj_t * ui_SaveGarden_Btn;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_ContainerGardenname;
extern lv_obj_t * ui_GardenNameTextArea;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_KeyboardGardenName;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

