// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CAPTURE_H
#define UI_CAPTURE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Capture
extern void ui_Capture_screen_init(void);
extern void ui_Capture_screen_destroy(void);
extern lv_obj_t * ui_Capture;
extern lv_obj_t * ui_text;
extern lv_obj_t * ui_ColorBox;
extern lv_obj_t * ui_CaptureBar;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern void ui_event_Label16(lv_event_t * e);
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_SmartText1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_tillerText;
extern lv_obj_t * ui_panicleText;
extern lv_obj_t * ui_panicleText1;
extern lv_obj_t * ui_panicleText2;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_GroupValue;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_RValue;
extern lv_obj_t * ui_GValue;
extern lv_obj_t * ui_BValue;
extern lv_obj_t * ui_CaptureButton;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_CapturePanel;
extern lv_obj_t * ui_CaptureStatusText;
extern lv_obj_t * ui_Latvalue;
extern lv_obj_t * ui_Lngvalue;
extern lv_obj_t * ui_Capturecontain;
extern lv_obj_t * ui_CaptureBlurPanel1;
extern lv_obj_t * ui_CapturePanel1;
extern lv_obj_t * ui_CaptureStatusText1;
extern void ui_event_CaptureCloseBtn(lv_event_t * e);
extern lv_obj_t * ui_CaptureCloseBtn;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Savecontain;
extern lv_obj_t * ui_CaptureBlurPanel2;
extern lv_obj_t * ui_CapturePanel2;
extern lv_obj_t * ui_CaptureStatusText2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

