// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Garden = NULL;
lv_obj_t * ui_GardenTopBar = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_GardenText = NULL;
lv_obj_t * ui_BlurPanel = NULL;
lv_obj_t * ui_Deleteconfirmpanel = NULL;
lv_obj_t * ui_DeleteConfirmText = NULL;
lv_obj_t * ui_Cancelbtn = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Confirmlbtn = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_AddGarden = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Containergar1 = NULL;
lv_obj_t * ui_GardenDeleteBtn1 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_GardenBtn1 = NULL;
lv_obj_t * ui_GardenName1 = NULL;
lv_obj_t * ui_Containergar2 = NULL;
lv_obj_t * ui_GardenDeleteBtn2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_GardenBtn2 = NULL;
lv_obj_t * ui_GardenName2 = NULL;
lv_obj_t * ui_Containergar3 = NULL;
lv_obj_t * ui_GardenDeleteBtn3 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_GardenBtn3 = NULL;
lv_obj_t * ui_GardenName3 = NULL;
lv_obj_t * ui_Containergar4 = NULL;
lv_obj_t * ui_GardenDeleteBtn4 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_GardenBtn4 = NULL;
lv_obj_t * ui_GardenName4 = NULL;
lv_obj_t * ui_Containergar5 = NULL;
lv_obj_t * ui_GardenDeleteBtn5 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_GardenBtn5 = NULL;
lv_obj_t * ui_GardenName5 = NULL;
lv_obj_t * ui_Gardencontain = NULL;
lv_obj_t * ui_CaptureBlurPanel3 = NULL;
lv_obj_t * ui_CapturePanel3 = NULL;
lv_obj_t * ui_CaptureStatusText3 = NULL;
lv_obj_t * ui_CaptureCloseBtn1 = NULL;
lv_obj_t * ui_Label29 = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

void ui_event_CaptureCloseBtn1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_Gardencontain, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Garden_screen_init(void)
{
    ui_Garden = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Garden, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenTopBar = lv_obj_create(ui_Garden);
    lv_obj_set_width(ui_GardenTopBar, 240);
    lv_obj_set_height(ui_GardenTopBar, 49);
    lv_obj_set_x(ui_GardenTopBar, 0);
    lv_obj_set_y(ui_GardenTopBar, -136);
    lv_obj_set_align(ui_GardenTopBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_GardenTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenTopBar, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenTopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_GardenTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_GardenTopBar);
    lv_obj_set_width(ui_Button5, 29);
    lv_obj_set_height(ui_Button5, 33);
    lv_obj_set_x(ui_Button5, -94);
    lv_obj_set_y(ui_Button5, 0);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "<");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_SFPROEN_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenText = lv_label_create(ui_GardenTopBar);
    lv_obj_set_width(ui_GardenText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GardenText, -42);
    lv_obj_set_y(ui_GardenText, 1);
    lv_obj_set_align(ui_GardenText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenText, "Garden");
    lv_obj_set_style_text_font(ui_GardenText, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BlurPanel = lv_obj_create(ui_Garden);
    lv_obj_set_width(ui_BlurPanel, 237);
    lv_obj_set_height(ui_BlurPanel, 316);
    lv_obj_set_align(ui_BlurPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BlurPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_BlurPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BlurPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BlurPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BlurPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_BlurPanel, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Deleteconfirmpanel = lv_obj_create(ui_Garden);
    lv_obj_set_width(ui_Deleteconfirmpanel, 187);
    lv_obj_set_height(ui_Deleteconfirmpanel, 159);
    lv_obj_set_align(ui_Deleteconfirmpanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Deleteconfirmpanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Deleteconfirmpanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Deleteconfirmpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Deleteconfirmpanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeleteConfirmText = lv_label_create(ui_Deleteconfirmpanel);
    lv_obj_set_width(ui_DeleteConfirmText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeleteConfirmText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeleteConfirmText, 0);
    lv_obj_set_y(ui_DeleteConfirmText, -47);
    lv_obj_set_align(ui_DeleteConfirmText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DeleteConfirmText, "ต้องการลบหรือไม่");
    lv_obj_set_style_text_font(ui_DeleteConfirmText, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cancelbtn = lv_btn_create(ui_Deleteconfirmpanel);
    lv_obj_set_width(ui_Cancelbtn, 73);
    lv_obj_set_height(ui_Cancelbtn, 41);
    lv_obj_set_x(ui_Cancelbtn, -50);
    lv_obj_set_y(ui_Cancelbtn, 41);
    lv_obj_set_align(ui_Cancelbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cancelbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Cancelbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Cancelbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Cancelbtn, lv_color_hex(0xBB0B0B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cancelbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Cancelbtn);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "ยกเลิก");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Confirmlbtn = lv_btn_create(ui_Deleteconfirmpanel);
    lv_obj_set_width(ui_Confirmlbtn, 73);
    lv_obj_set_height(ui_Confirmlbtn, 41);
    lv_obj_set_x(ui_Confirmlbtn, 48);
    lv_obj_set_y(ui_Confirmlbtn, 40);
    lv_obj_set_align(ui_Confirmlbtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Confirmlbtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Confirmlbtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Confirmlbtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Confirmlbtn, lv_color_hex(0x48A307), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Confirmlbtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Confirmlbtn);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "ลบ");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AddGarden = lv_btn_create(ui_Garden);
    lv_obj_set_width(ui_AddGarden, 75);
    lv_obj_set_height(ui_AddGarden, 47);
    lv_obj_set_x(ui_AddGarden, -71);
    lv_obj_set_y(ui_AddGarden, 129);
    lv_obj_set_align(ui_AddGarden, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AddGarden, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AddGarden, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AddGarden, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AddGarden, lv_color_hex(0x3399D2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AddGarden, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_AddGarden);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "+");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containergar1 = lv_obj_create(ui_Garden);
    lv_obj_remove_style_all(ui_Containergar1);
    lv_obj_set_width(ui_Containergar1, 220);
    lv_obj_set_height(ui_Containergar1, 42);
    lv_obj_set_x(ui_Containergar1, 0);
    lv_obj_set_y(ui_Containergar1, -80);
    lv_obj_set_align(ui_Containergar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containergar1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenDeleteBtn1 = lv_btn_create(ui_Containergar1);
    lv_obj_set_width(ui_GardenDeleteBtn1, 61);
    lv_obj_set_height(ui_GardenDeleteBtn1, 35);
    lv_obj_set_x(ui_GardenDeleteBtn1, 79);
    lv_obj_set_y(ui_GardenDeleteBtn1, 1);
    lv_obj_set_align(ui_GardenDeleteBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenDeleteBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenDeleteBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenDeleteBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenDeleteBtn1, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenDeleteBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image12 = lv_img_create(ui_GardenDeleteBtn1);
    lv_img_set_src(ui_Image12, &ui_img_trash_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenBtn1 = lv_btn_create(ui_Containergar1);
    lv_obj_set_width(ui_GardenBtn1, 151);
    lv_obj_set_height(ui_GardenBtn1, 34);
    lv_obj_set_x(ui_GardenBtn1, -32);
    lv_obj_set_y(ui_GardenBtn1, 1);
    lv_obj_set_align(ui_GardenBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenBtn1, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenName1 = lv_label_create(ui_GardenBtn1);
    lv_obj_set_width(ui_GardenName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GardenName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenName1, "Gardenname1");
    lv_obj_set_style_text_font(ui_GardenName1, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containergar2 = lv_obj_create(ui_Garden);
    lv_obj_remove_style_all(ui_Containergar2);
    lv_obj_set_width(ui_Containergar2, 220);
    lv_obj_set_height(ui_Containergar2, 42);
    lv_obj_set_x(ui_Containergar2, -1);
    lv_obj_set_y(ui_Containergar2, -41);
    lv_obj_set_align(ui_Containergar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containergar2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenDeleteBtn2 = lv_btn_create(ui_Containergar2);
    lv_obj_set_width(ui_GardenDeleteBtn2, 61);
    lv_obj_set_height(ui_GardenDeleteBtn2, 35);
    lv_obj_set_x(ui_GardenDeleteBtn2, 79);
    lv_obj_set_y(ui_GardenDeleteBtn2, 1);
    lv_obj_set_align(ui_GardenDeleteBtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenDeleteBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenDeleteBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenDeleteBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenDeleteBtn2, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenDeleteBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_GardenDeleteBtn2);
    lv_img_set_src(ui_Image2, &ui_img_trash_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenBtn2 = lv_btn_create(ui_Containergar2);
    lv_obj_set_width(ui_GardenBtn2, 151);
    lv_obj_set_height(ui_GardenBtn2, 34);
    lv_obj_set_x(ui_GardenBtn2, -32);
    lv_obj_set_y(ui_GardenBtn2, 1);
    lv_obj_set_align(ui_GardenBtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenBtn2, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenName2 = lv_label_create(ui_GardenBtn2);
    lv_obj_set_width(ui_GardenName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GardenName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenName2, "Gardenname1");
    lv_obj_set_style_text_font(ui_GardenName2, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containergar3 = lv_obj_create(ui_Garden);
    lv_obj_remove_style_all(ui_Containergar3);
    lv_obj_set_width(ui_Containergar3, 220);
    lv_obj_set_height(ui_Containergar3, 42);
    lv_obj_set_x(ui_Containergar3, -1);
    lv_obj_set_y(ui_Containergar3, -1);
    lv_obj_set_align(ui_Containergar3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containergar3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenDeleteBtn3 = lv_btn_create(ui_Containergar3);
    lv_obj_set_width(ui_GardenDeleteBtn3, 61);
    lv_obj_set_height(ui_GardenDeleteBtn3, 35);
    lv_obj_set_x(ui_GardenDeleteBtn3, 79);
    lv_obj_set_y(ui_GardenDeleteBtn3, 1);
    lv_obj_set_align(ui_GardenDeleteBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenDeleteBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenDeleteBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenDeleteBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenDeleteBtn3, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenDeleteBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_GardenDeleteBtn3);
    lv_img_set_src(ui_Image3, &ui_img_trash_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenBtn3 = lv_btn_create(ui_Containergar3);
    lv_obj_set_width(ui_GardenBtn3, 151);
    lv_obj_set_height(ui_GardenBtn3, 34);
    lv_obj_set_x(ui_GardenBtn3, -32);
    lv_obj_set_y(ui_GardenBtn3, 1);
    lv_obj_set_align(ui_GardenBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenBtn3, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenName3 = lv_label_create(ui_GardenBtn3);
    lv_obj_set_width(ui_GardenName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GardenName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenName3, "Gardenname1");
    lv_obj_set_style_text_font(ui_GardenName3, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containergar4 = lv_obj_create(ui_Garden);
    lv_obj_remove_style_all(ui_Containergar4);
    lv_obj_set_width(ui_Containergar4, 220);
    lv_obj_set_height(ui_Containergar4, 42);
    lv_obj_set_x(ui_Containergar4, -1);
    lv_obj_set_y(ui_Containergar4, 37);
    lv_obj_set_align(ui_Containergar4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containergar4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenDeleteBtn4 = lv_btn_create(ui_Containergar4);
    lv_obj_set_width(ui_GardenDeleteBtn4, 61);
    lv_obj_set_height(ui_GardenDeleteBtn4, 35);
    lv_obj_set_x(ui_GardenDeleteBtn4, 79);
    lv_obj_set_y(ui_GardenDeleteBtn4, 1);
    lv_obj_set_align(ui_GardenDeleteBtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenDeleteBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenDeleteBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenDeleteBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenDeleteBtn4, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenDeleteBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_GardenDeleteBtn4);
    lv_img_set_src(ui_Image4, &ui_img_trash_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenBtn4 = lv_btn_create(ui_Containergar4);
    lv_obj_set_width(ui_GardenBtn4, 151);
    lv_obj_set_height(ui_GardenBtn4, 34);
    lv_obj_set_x(ui_GardenBtn4, -32);
    lv_obj_set_y(ui_GardenBtn4, 1);
    lv_obj_set_align(ui_GardenBtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenBtn4, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenName4 = lv_label_create(ui_GardenBtn4);
    lv_obj_set_width(ui_GardenName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GardenName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenName4, "Gardenname1");
    lv_obj_set_style_text_font(ui_GardenName4, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Containergar5 = lv_obj_create(ui_Garden);
    lv_obj_remove_style_all(ui_Containergar5);
    lv_obj_set_width(ui_Containergar5, 220);
    lv_obj_set_height(ui_Containergar5, 42);
    lv_obj_set_x(ui_Containergar5, -1);
    lv_obj_set_y(ui_Containergar5, 75);
    lv_obj_set_align(ui_Containergar5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Containergar5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenDeleteBtn5 = lv_btn_create(ui_Containergar5);
    lv_obj_set_width(ui_GardenDeleteBtn5, 61);
    lv_obj_set_height(ui_GardenDeleteBtn5, 35);
    lv_obj_set_x(ui_GardenDeleteBtn5, 79);
    lv_obj_set_y(ui_GardenDeleteBtn5, 1);
    lv_obj_set_align(ui_GardenDeleteBtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenDeleteBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenDeleteBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenDeleteBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenDeleteBtn5, lv_color_hex(0xBD0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenDeleteBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_GardenDeleteBtn5);
    lv_img_set_src(ui_Image5, &ui_img_trash_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GardenBtn5 = lv_btn_create(ui_Containergar5);
    lv_obj_set_width(ui_GardenBtn5, 151);
    lv_obj_set_height(ui_GardenBtn5, 34);
    lv_obj_set_x(ui_GardenBtn5, -32);
    lv_obj_set_y(ui_GardenBtn5, 1);
    lv_obj_set_align(ui_GardenBtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GardenBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GardenBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GardenBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_GardenBtn5, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GardenBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GardenName5 = lv_label_create(ui_GardenBtn5);
    lv_obj_set_width(ui_GardenName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GardenName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenName5, "Gardenname1");
    lv_obj_set_style_text_font(ui_GardenName5, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gardencontain = lv_obj_create(ui_Garden);
    lv_obj_remove_style_all(ui_Gardencontain);
    lv_obj_set_width(ui_Gardencontain, 240);
    lv_obj_set_height(ui_Gardencontain, 320);
    lv_obj_set_align(ui_Gardencontain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gardencontain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Gardencontain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CaptureBlurPanel3 = lv_obj_create(ui_Gardencontain);
    lv_obj_set_width(ui_CaptureBlurPanel3, 240);
    lv_obj_set_height(ui_CaptureBlurPanel3, 320);
    lv_obj_set_align(ui_CaptureBlurPanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CaptureBlurPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureBlurPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureBlurPanel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureBlurPanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CaptureBlurPanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_CaptureBlurPanel3, 1500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CapturePanel3 = lv_obj_create(ui_Gardencontain);
    lv_obj_set_width(ui_CapturePanel3, 221);
    lv_obj_set_height(ui_CapturePanel3, 147);
    lv_obj_set_align(ui_CapturePanel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CapturePanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CapturePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CapturePanel3, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CapturePanel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_CapturePanel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureStatusText3 = lv_label_create(ui_CapturePanel3);
    lv_obj_set_width(ui_CaptureStatusText3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CaptureStatusText3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CaptureStatusText3, 0);
    lv_obj_set_y(ui_CaptureStatusText3, -22);
    lv_obj_set_align(ui_CaptureStatusText3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CaptureStatusText3, "ไม่มีสัญญาณ GPS");
    lv_obj_set_style_text_font(ui_CaptureStatusText3, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CaptureCloseBtn1 = lv_btn_create(ui_Gardencontain);
    lv_obj_set_width(ui_CaptureCloseBtn1, 100);
    lv_obj_set_height(ui_CaptureCloseBtn1, 39);
    lv_obj_set_x(ui_CaptureCloseBtn1, 0);
    lv_obj_set_y(ui_CaptureCloseBtn1, 41);
    lv_obj_set_align(ui_CaptureCloseBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CaptureCloseBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CaptureCloseBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CaptureCloseBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CaptureCloseBtn1, lv_color_hex(0xB50000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CaptureCloseBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_CaptureCloseBtn1);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "รับทราบ");
    lv_obj_set_style_text_font(ui_Label29, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CaptureCloseBtn1, ui_event_CaptureCloseBtn1, LV_EVENT_ALL, NULL);

}

void ui_Garden_screen_destroy(void)
{
    if(ui_Garden) lv_obj_del(ui_Garden);

    // NULL screen variables
    ui_Garden = NULL;
    ui_GardenTopBar = NULL;
    ui_Button5 = NULL;
    ui_Label11 = NULL;
    ui_GardenText = NULL;
    ui_BlurPanel = NULL;
    ui_Deleteconfirmpanel = NULL;
    ui_DeleteConfirmText = NULL;
    ui_Cancelbtn = NULL;
    ui_Label12 = NULL;
    ui_Confirmlbtn = NULL;
    ui_Label13 = NULL;
    ui_AddGarden = NULL;
    ui_Label15 = NULL;
    ui_Containergar1 = NULL;
    ui_GardenDeleteBtn1 = NULL;
    ui_Image12 = NULL;
    ui_GardenBtn1 = NULL;
    ui_GardenName1 = NULL;
    ui_Containergar2 = NULL;
    ui_GardenDeleteBtn2 = NULL;
    ui_Image2 = NULL;
    ui_GardenBtn2 = NULL;
    ui_GardenName2 = NULL;
    ui_Containergar3 = NULL;
    ui_GardenDeleteBtn3 = NULL;
    ui_Image3 = NULL;
    ui_GardenBtn3 = NULL;
    ui_GardenName3 = NULL;
    ui_Containergar4 = NULL;
    ui_GardenDeleteBtn4 = NULL;
    ui_Image4 = NULL;
    ui_GardenBtn4 = NULL;
    ui_GardenName4 = NULL;
    ui_Containergar5 = NULL;
    ui_GardenDeleteBtn5 = NULL;
    ui_Image5 = NULL;
    ui_GardenBtn5 = NULL;
    ui_GardenName5 = NULL;
    ui_Gardencontain = NULL;
    ui_CaptureBlurPanel3 = NULL;
    ui_CapturePanel3 = NULL;
    ui_CaptureStatusText3 = NULL;
    ui_CaptureCloseBtn1 = NULL;
    ui_Label29 = NULL;

}
