// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_GARDEN_H
#define UI_GARDEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Garden
extern void ui_Garden_screen_init(void);
extern void ui_Garden_screen_destroy(void);
extern lv_obj_t * ui_Garden;
extern lv_obj_t * ui_GardenTopBar;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_GardenText;
extern lv_obj_t * ui_BlurPanel;
extern lv_obj_t * ui_Deleteconfirmpanel;
extern lv_obj_t * ui_DeleteConfirmText;
extern lv_obj_t * ui_Cancelbtn;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Confirmlbtn;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_AddGarden;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Containergar1;
extern lv_obj_t * ui_GardenDeleteBtn1;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_GardenBtn1;
extern lv_obj_t * ui_GardenName1;
extern lv_obj_t * ui_Containergar2;
extern lv_obj_t * ui_GardenDeleteBtn2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_GardenBtn2;
extern lv_obj_t * ui_GardenName2;
extern lv_obj_t * ui_Containergar3;
extern lv_obj_t * ui_GardenDeleteBtn3;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_GardenBtn3;
extern lv_obj_t * ui_GardenName3;
extern lv_obj_t * ui_Containergar4;
extern lv_obj_t * ui_GardenDeleteBtn4;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_GardenBtn4;
extern lv_obj_t * ui_GardenName4;
extern lv_obj_t * ui_Containergar5;
extern lv_obj_t * ui_GardenDeleteBtn5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_GardenBtn5;
extern lv_obj_t * ui_GardenName5;
extern lv_obj_t * ui_Gardencontain;
extern lv_obj_t * ui_CaptureBlurPanel3;
extern lv_obj_t * ui_CapturePanel3;
extern lv_obj_t * ui_CaptureStatusText3;
extern void ui_event_CaptureCloseBtn1(lv_event_t * e);
extern lv_obj_t * ui_CaptureCloseBtn1;
extern lv_obj_t * ui_Label29;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

