// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_LoginWifi = NULL;
lv_obj_t * ui_WifiTopBar1 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_SelectWIFLoginText = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_WIFIpassword = NULL;
lv_obj_t * ui_WifiName = NULL;
lv_obj_t * ui_Wificontain = NULL;
lv_obj_t * ui_WifiBlurPanel = NULL;
lv_obj_t * ui_WifiPanel = NULL;
lv_obj_t * ui_WifiStatusText = NULL;
// event funtions
void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SelectWifi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SelectWifi_screen_init);
    }
}

// build funtions

void ui_LoginWifi_screen_init(void)
{
    ui_LoginWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LoginWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiTopBar1 = lv_obj_create(ui_LoginWifi);
    lv_obj_set_width(ui_WifiTopBar1, 240);
    lv_obj_set_height(ui_WifiTopBar1, 49);
    lv_obj_set_x(ui_WifiTopBar1, 0);
    lv_obj_set_y(ui_WifiTopBar1, -136);
    lv_obj_set_align(ui_WifiTopBar1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiTopBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiTopBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTopBar1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTopBar1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTopBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_WifiTopBar1);
    lv_obj_set_width(ui_Button6, 29);
    lv_obj_set_height(ui_Button6, 33);
    lv_obj_set_x(ui_Button6, -94);
    lv_obj_set_y(ui_Button6, 0);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "<");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_SFPROEN_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectWIFLoginText = lv_label_create(ui_WifiTopBar1);
    lv_obj_set_width(ui_SelectWIFLoginText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectWIFLoginText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectWIFLoginText, 34);
    lv_obj_set_y(ui_SelectWIFLoginText, 2);
    lv_obj_set_align(ui_SelectWIFLoginText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SelectWIFLoginText, "Login");
    lv_obj_set_style_text_align(ui_SelectWIFLoginText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelectWIFLoginText, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_LoginWifi);
    lv_obj_set_width(ui_Keyboard1, 236);
    lv_obj_set_height(ui_Keyboard1, 101);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 99);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);

    ui_WIFIpassword = lv_textarea_create(ui_LoginWifi);
    lv_obj_set_width(ui_WIFIpassword, 215);
    lv_obj_set_height(ui_WIFIpassword, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_WIFIpassword, -2);
    lv_obj_set_y(ui_WIFIpassword, -6);
    lv_obj_set_align(ui_WIFIpassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WIFIpassword, "Password");
    lv_textarea_set_one_line(ui_WIFIpassword, true);

    ui_WifiName = lv_label_create(ui_LoginWifi);
    lv_obj_set_width(ui_WifiName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiName, 0);
    lv_obj_set_y(ui_WifiName, -65);
    lv_obj_set_align(ui_WifiName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName, "MudengMuhahahaha");
    lv_obj_set_style_text_font(ui_WifiName, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wificontain = lv_obj_create(ui_LoginWifi);
    lv_obj_remove_style_all(ui_Wificontain);
    lv_obj_set_width(ui_Wificontain, 240);
    lv_obj_set_height(ui_Wificontain, 320);
    lv_obj_set_align(ui_Wificontain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wificontain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Wificontain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiBlurPanel = lv_obj_create(ui_Wificontain);
    lv_obj_set_width(ui_WifiBlurPanel, 240);
    lv_obj_set_height(ui_WifiBlurPanel, 320);
    lv_obj_set_align(ui_WifiBlurPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiBlurPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiBlurPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiBlurPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiBlurPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiBlurPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_WifiBlurPanel, 1500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPanel = lv_obj_create(ui_Wificontain);
    lv_obj_set_width(ui_WifiPanel, 221);
    lv_obj_set_height(ui_WifiPanel, 147);
    lv_obj_set_align(ui_WifiPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiPanel, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatusText = lv_label_create(ui_WifiPanel);
    lv_obj_set_width(ui_WifiStatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiStatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiStatusText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiStatusText, "กำลังเชื่อมต่อ...");
    lv_obj_set_style_text_font(ui_WifiStatusText, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_WIFIpassword);

}

void ui_LoginWifi_screen_destroy(void)
{
    if(ui_LoginWifi) lv_obj_del(ui_LoginWifi);

    // NULL screen variables
    ui_LoginWifi = NULL;
    ui_WifiTopBar1 = NULL;
    ui_Button6 = NULL;
    ui_Label14 = NULL;
    ui_SelectWIFLoginText = NULL;
    ui_Keyboard1 = NULL;
    ui_WIFIpassword = NULL;
    ui_WifiName = NULL;
    ui_Wificontain = NULL;
    ui_WifiBlurPanel = NULL;
    ui_WifiPanel = NULL;
    ui_WifiStatusText = NULL;

}
