// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LINE_H
#define UI_LINE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Line
extern void ui_Line_screen_init(void);
extern void ui_Line_screen_destroy(void);
extern lv_obj_t * ui_Line;
extern lv_obj_t * ui_WifiTopBar3;
extern lv_obj_t * ui_LineText;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_SmartTipText2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_SerialText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

