// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LOGINWIFI_H
#define UI_LOGINWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoginWifi
extern void ui_LoginWifi_screen_init(void);
extern void ui_LoginWifi_screen_destroy(void);
extern lv_obj_t * ui_LoginWifi;
extern lv_obj_t * ui_WifiTopBar1;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_SelectWIFLoginText;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui_WIFIpassword;
extern lv_obj_t * ui_WifiName;
extern lv_obj_t * ui_Wificontain;
extern lv_obj_t * ui_WifiBlurPanel;
extern lv_obj_t * ui_WifiPanel;
extern lv_obj_t * ui_WifiStatusText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

