// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Line = NULL;
lv_obj_t * ui_WifiTopBar3 = NULL;
lv_obj_t * ui_LineText = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_SmartTipText2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_SerialText = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_Line_screen_init(void)
{
    ui_Line = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiTopBar3 = lv_obj_create(ui_Line);
    lv_obj_set_width(ui_WifiTopBar3, 240);
    lv_obj_set_height(ui_WifiTopBar3, 49);
    lv_obj_set_x(ui_WifiTopBar3, 0);
    lv_obj_set_y(ui_WifiTopBar3, -136);
    lv_obj_set_align(ui_WifiTopBar3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiTopBar3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiTopBar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTopBar3, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTopBar3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTopBar3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LineText = lv_label_create(ui_WifiTopBar3);
    lv_obj_set_width(ui_LineText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LineText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LineText, -49);
    lv_obj_set_y(ui_LineText, 0);
    lv_obj_set_align(ui_LineText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LineText, "Line");
    lv_obj_set_style_text_font(ui_LineText, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_WifiTopBar3);
    lv_obj_set_width(ui_Button3, 29);
    lv_obj_set_height(ui_Button3, 33);
    lv_obj_set_x(ui_Button3, -94);
    lv_obj_set_y(ui_Button3, 0);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "<");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_SFPROEN_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Line);
    lv_img_set_src(ui_Image10, &ui_img_lineqrcode_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 143
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 143
    lv_obj_set_x(ui_Image10, 0);
    lv_obj_set_y(ui_Image10, -26);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SmartTipText2 = lv_label_create(ui_Line);
    lv_obj_set_width(ui_SmartTipText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartTipText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartTipText2, 0);
    lv_obj_set_y(ui_SmartTipText2, 79);
    lv_obj_set_align(ui_SmartTipText2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartTipText2,
                      "โปรดแสกนคิวอาร์โค้ด\nและผูกบัญชีเครื่องกับไลน์");
    lv_obj_set_style_text_align(ui_SmartTipText2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SmartTipText2, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Line);
    lv_obj_set_width(ui_Panel2, 187);
    lv_obj_set_height(ui_Panel2, 35);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 129);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SerialText = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_SerialText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SerialText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SerialText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SerialText, "8HI9L70C");
    lv_obj_set_style_text_font(ui_SerialText, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Line_screen_destroy(void)
{
    if(ui_Line) lv_obj_del(ui_Line);

    // NULL screen variables
    ui_Line = NULL;
    ui_WifiTopBar3 = NULL;
    ui_LineText = NULL;
    ui_Button3 = NULL;
    ui_Label9 = NULL;
    ui_Image10 = NULL;
    ui_SmartTipText2 = NULL;
    ui_Panel2 = NULL;
    ui_SerialText = NULL;

}
