// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Gardenbutton = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Gpsicon = NULL;
lv_obj_t * ui_Colorbutton = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Wiconon = NULL;
lv_obj_t * ui_Wiconoff = NULL;
lv_obj_t * ui_Batteryicon = NULL;
lv_obj_t * ui_Betterypercenttext = NULL;
lv_obj_t * ui_Guidebutton = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Wifibutton = NULL;
lv_obj_t * ui_Wifiicon = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Cloudbutton = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Cloudicon = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Gpsiconoff = NULL;
lv_obj_t * ui_Gpsiconon = NULL;
lv_obj_t * ui_StatusColor = NULL;
lv_obj_t * ui_MenuStatusText = NULL;
// event funtions
void ui_event_Gardenbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Garden, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Garden_screen_init);
    }
}

void ui_event_Colorbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Capture, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Capture_screen_init);
    }
}

void ui_event_Guidebutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Line, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Line_screen_init);
    }
}

void ui_event_Wifibutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SelectWifi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_SelectWifi_screen_init);
    }
}

void ui_event_Cloudbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Smart, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Smart_screen_init);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Gardenbutton = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Gardenbutton, 70);
    lv_obj_set_height(ui_Gardenbutton, 97);
    lv_obj_set_x(ui_Gardenbutton, -73);
    lv_obj_set_y(ui_Gardenbutton, 100);
    lv_obj_set_align(ui_Gardenbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gardenbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Gardenbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Gardenbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Gardenbutton, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Gardenbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Gardenbutton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 27);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "แปลง");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Gpsicon = lv_img_create(ui_Gardenbutton);
    lv_img_set_src(ui_Gpsicon, &ui_img_marker_png);
    lv_obj_set_width(ui_Gpsicon, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Gpsicon, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Gpsicon, 0);
    lv_obj_set_y(ui_Gpsicon, -20);
    lv_obj_set_align(ui_Gpsicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gpsicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gpsicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Colorbutton = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Colorbutton, 143);
    lv_obj_set_height(ui_Colorbutton, 169);
    lv_obj_set_x(ui_Colorbutton, -37);
    lv_obj_set_y(ui_Colorbutton, -37);
    lv_obj_set_align(ui_Colorbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Colorbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Colorbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Colorbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Colorbutton, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Colorbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Colorbutton);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 67);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "เก็บค่าสี");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wiconon = lv_img_create(ui_Menu);
    lv_img_set_src(ui_Wiconon, &ui_img_wifion_png);
    lv_obj_set_width(ui_Wiconon, LV_SIZE_CONTENT);   /// 63
    lv_obj_set_height(ui_Wiconon, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_Wiconon, 94);
    lv_obj_set_y(ui_Wiconon, -143);
    lv_obj_set_align(ui_Wiconon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wiconon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wiconon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Wiconon, 200);

    ui_Wiconoff = lv_img_create(ui_Menu);
    lv_img_set_src(ui_Wiconoff, &ui_img_wifioff_png);
    lv_obj_set_width(ui_Wiconoff, LV_SIZE_CONTENT);   /// 37
    lv_obj_set_height(ui_Wiconoff, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Wiconoff, 94);
    lv_obj_set_y(ui_Wiconoff, -144);
    lv_obj_set_align(ui_Wiconoff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wiconoff, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wiconoff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Wiconoff, 200);

    ui_Batteryicon = lv_img_create(ui_Menu);
    lv_img_set_src(ui_Batteryicon, &ui_img_battery_png);
    lv_obj_set_width(ui_Batteryicon, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_Batteryicon, LV_SIZE_CONTENT);    /// 26
    lv_obj_set_x(ui_Batteryicon, 53);
    lv_obj_set_y(ui_Batteryicon, -143);
    lv_obj_set_align(ui_Batteryicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Batteryicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Batteryicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Batteryicon, 200);

    ui_Betterypercenttext = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Betterypercenttext, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Betterypercenttext, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Betterypercenttext, 52);
    lv_obj_set_y(ui_Betterypercenttext, -143);
    lv_obj_set_align(ui_Betterypercenttext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Betterypercenttext, "100");
    lv_obj_set_style_text_font(ui_Betterypercenttext, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Guidebutton = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Guidebutton, 70);
    lv_obj_set_height(ui_Guidebutton, 97);
    lv_obj_set_x(ui_Guidebutton, 73);
    lv_obj_set_y(ui_Guidebutton, 100);
    lv_obj_set_align(ui_Guidebutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Guidebutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Guidebutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Guidebutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Guidebutton, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Guidebutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Guidebutton);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 30);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "LINE");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Guidebutton);
    lv_img_set_src(ui_Image1, &ui_img_line_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -20);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifibutton = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Wifibutton, 70);
    lv_obj_set_height(ui_Wifibutton, 97);
    lv_obj_set_x(ui_Wifibutton, 0);
    lv_obj_set_y(ui_Wifibutton, 100);
    lv_obj_set_align(ui_Wifibutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifibutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Wifibutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifibutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifibutton, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifibutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifiicon = lv_img_create(ui_Wifibutton);
    lv_img_set_src(ui_Wifiicon, &ui_img_159797012);
    lv_obj_set_width(ui_Wifiicon, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Wifiicon, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Wifiicon, 0);
    lv_obj_set_y(ui_Wifiicon, -20);
    lv_obj_set_align(ui_Wifiicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wifiicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wifiicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Wifibutton);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 30);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "WIFI");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cloudbutton = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Cloudbutton, 70);
    lv_obj_set_height(ui_Cloudbutton, 169);
    lv_obj_set_x(ui_Cloudbutton, 73);
    lv_obj_set_y(ui_Cloudbutton, -37);
    lv_obj_set_align(ui_Cloudbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cloudbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Cloudbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Cloudbutton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Cloudbutton, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Cloudbutton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Cloudbutton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, 52);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "ติดตาม\nผล");
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_SFPROTH_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Cloudicon = lv_img_create(ui_Cloudbutton);
    lv_img_set_src(ui_Cloudicon, &ui_img_1039951338);
    lv_obj_set_width(ui_Cloudicon, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_Cloudicon, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Cloudicon, 0);
    lv_obj_set_y(ui_Cloudicon, -20);
    lv_obj_set_align(ui_Cloudicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cloudicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Cloudicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Menu);
    lv_img_set_src(ui_Image6, &ui_img_leave_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_Image6, -38);
    lv_obj_set_y(ui_Image6, -53);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Gpsiconoff = lv_img_create(ui_Menu);
    lv_img_set_src(ui_Gpsiconoff, &ui_img_nogps_png);
    lv_obj_set_width(ui_Gpsiconoff, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Gpsiconoff, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_Gpsiconoff, 16);
    lv_obj_set_y(ui_Gpsiconoff, -144);
    lv_obj_set_align(ui_Gpsiconoff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gpsiconoff, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gpsiconoff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Gpsiconoff, 200);

    ui_Gpsiconon = lv_img_create(ui_Menu);
    lv_img_set_src(ui_Gpsiconon, &ui_img_gps_png);
    lv_obj_set_width(ui_Gpsiconon, LV_SIZE_CONTENT);   /// 24
    lv_obj_set_height(ui_Gpsiconon, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_Gpsiconon, 16);
    lv_obj_set_y(ui_Gpsiconon, -144);
    lv_obj_set_align(ui_Gpsiconon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Gpsiconon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Gpsiconon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Gpsiconon, 200);

    ui_StatusColor = lv_obj_create(ui_Menu);
    lv_obj_set_width(ui_StatusColor, 25);
    lv_obj_set_height(ui_StatusColor, 25);
    lv_obj_set_x(ui_StatusColor, -94);
    lv_obj_set_y(ui_StatusColor, -141);
    lv_obj_set_align(ui_StatusColor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusColor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatusColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusColor, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusColor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_StatusColor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuStatusText = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_MenuStatusText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuStatusText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MenuStatusText, 45);
    lv_obj_set_y(ui_MenuStatusText, -141);
    lv_obj_set_align(ui_MenuStatusText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MenuStatusText, "ล่าสุด");
    lv_obj_set_style_text_color(ui_MenuStatusText, lv_color_hex(0x31FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MenuStatusText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MenuStatusText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MenuStatusText, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuStatusText, &ui_font_THNEW_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Gardenbutton, ui_event_Gardenbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Colorbutton, ui_event_Colorbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Guidebutton, ui_event_Guidebutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifibutton, ui_event_Wifibutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Cloudbutton, ui_event_Cloudbutton, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    ui_Menu = NULL;
    ui_Gardenbutton = NULL;
    ui_Label2 = NULL;
    ui_Gpsicon = NULL;
    ui_Colorbutton = NULL;
    ui_Label1 = NULL;
    ui_Wiconon = NULL;
    ui_Wiconoff = NULL;
    ui_Batteryicon = NULL;
    ui_Betterypercenttext = NULL;
    ui_Guidebutton = NULL;
    ui_Label4 = NULL;
    ui_Image1 = NULL;
    ui_Wifibutton = NULL;
    ui_Wifiicon = NULL;
    ui_Label3 = NULL;
    ui_Cloudbutton = NULL;
    ui_Label5 = NULL;
    ui_Cloudicon = NULL;
    ui_Image6 = NULL;
    ui_Gpsiconoff = NULL;
    ui_Gpsiconon = NULL;
    ui_StatusColor = NULL;
    ui_MenuStatusText = NULL;

}
