// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern lv_obj_t * ui_Menu;
extern void ui_event_Gardenbutton(lv_event_t * e);
extern lv_obj_t * ui_Gardenbutton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Gpsicon;
extern void ui_event_Colorbutton(lv_event_t * e);
extern lv_obj_t * ui_Colorbutton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Wiconon;
extern lv_obj_t * ui_Wiconoff;
extern lv_obj_t * ui_Batteryicon;
extern lv_obj_t * ui_Betterypercenttext;
extern void ui_event_Guidebutton(lv_event_t * e);
extern lv_obj_t * ui_Guidebutton;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image1;
extern void ui_event_Wifibutton(lv_event_t * e);
extern lv_obj_t * ui_Wifibutton;
extern lv_obj_t * ui_Wifiicon;
extern lv_obj_t * ui_Label3;
extern void ui_event_Cloudbutton(lv_event_t * e);
extern lv_obj_t * ui_Cloudbutton;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Cloudicon;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Gpsiconoff;
extern lv_obj_t * ui_Gpsiconon;
extern lv_obj_t * ui_StatusColor;
extern lv_obj_t * ui_MenuStatusText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

