// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SELECTWIFI_H
#define UI_SELECTWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SelectWifi
extern void ui_SelectWifi_screen_init(void);
extern void ui_SelectWifi_screen_destroy(void);
extern lv_obj_t * ui_SelectWifi;
extern lv_obj_t * ui_RefreshWifiBtn;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_WiFiBtn1;
extern lv_obj_t * ui_WifiName1;
extern lv_obj_t * ui_WiFiBtn2;
extern lv_obj_t * ui_WifiName2;
extern lv_obj_t * ui_WiFiBtn3;
extern lv_obj_t * ui_WifiName3;
extern lv_obj_t * ui_WiFiBtn4;
extern lv_obj_t * ui_WifiName4;
extern lv_obj_t * ui_WiFiBtn5;
extern lv_obj_t * ui_WifiName5;
extern lv_obj_t * ui_WiFiBtn6;
extern lv_obj_t * ui_WifiName6;
extern lv_obj_t * ui_WiFiBtn7;
extern lv_obj_t * ui_WifiName7;
extern lv_obj_t * ui_WiFiBtn8;
extern lv_obj_t * ui_WifiName8;
extern lv_obj_t * ui_WiFiBtn9;
extern lv_obj_t * ui_WifiName9;
extern lv_obj_t * ui_WiFiBtn10;
extern lv_obj_t * ui_WifiName10;
extern lv_obj_t * ui_WifiTopBar2;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_SelectWIFIText;
extern lv_obj_t * ui_WifiScancontain;
extern lv_obj_t * ui_WifiBlurPanel1;
extern lv_obj_t * ui_WifiPanel1;
extern lv_obj_t * ui_WifiScanText;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

