// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_SelectWifi = NULL;
lv_obj_t * ui_RefreshWifiBtn = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_WiFiBtn1 = NULL;
lv_obj_t * ui_WifiName1 = NULL;
lv_obj_t * ui_WiFiBtn2 = NULL;
lv_obj_t * ui_WifiName2 = NULL;
lv_obj_t * ui_WiFiBtn3 = NULL;
lv_obj_t * ui_WifiName3 = NULL;
lv_obj_t * ui_WiFiBtn4 = NULL;
lv_obj_t * ui_WifiName4 = NULL;
lv_obj_t * ui_WiFiBtn5 = NULL;
lv_obj_t * ui_WifiName5 = NULL;
lv_obj_t * ui_WiFiBtn6 = NULL;
lv_obj_t * ui_WifiName6 = NULL;
lv_obj_t * ui_WiFiBtn7 = NULL;
lv_obj_t * ui_WifiName7 = NULL;
lv_obj_t * ui_WiFiBtn8 = NULL;
lv_obj_t * ui_WifiName8 = NULL;
lv_obj_t * ui_WiFiBtn9 = NULL;
lv_obj_t * ui_WifiName9 = NULL;
lv_obj_t * ui_WiFiBtn10 = NULL;
lv_obj_t * ui_WifiName10 = NULL;
lv_obj_t * ui_WifiTopBar2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_SelectWIFIText = NULL;
lv_obj_t * ui_WifiScancontain = NULL;
lv_obj_t * ui_WifiBlurPanel1 = NULL;
lv_obj_t * ui_WifiPanel1 = NULL;
lv_obj_t * ui_WifiScanText = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_SelectWifi_screen_init(void)
{
    ui_SelectWifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RefreshWifiBtn = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_RefreshWifiBtn, 47);
    lv_obj_set_height(ui_RefreshWifiBtn, 45);
    lv_obj_set_x(ui_RefreshWifiBtn, 87);
    lv_obj_set_y(ui_RefreshWifiBtn, -77);
    lv_obj_set_align(ui_RefreshWifiBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RefreshWifiBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RefreshWifiBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RefreshWifiBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RefreshWifiBtn, lv_color_hex(0x292929), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RefreshWifiBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_SelectWifi);
    lv_img_set_src(ui_Image7, &ui_img_refresh_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 42
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_Image7, 88);
    lv_obj_set_y(ui_Image7, -77);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image7, 150);

    ui_WiFiBtn1 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn1, 151);
    lv_obj_set_height(ui_WiFiBtn1, 23);
    lv_obj_set_x(ui_WiFiBtn1, -29);
    lv_obj_set_y(ui_WiFiBtn1, -87);
    lv_obj_set_align(ui_WiFiBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn1, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName1 = lv_label_create(ui_WiFiBtn1);
    lv_obj_set_width(ui_WifiName1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName1, "SSID1");
    lv_obj_set_style_text_font(ui_WifiName1, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn2 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn2, 151);
    lv_obj_set_height(ui_WiFiBtn2, 23);
    lv_obj_set_x(ui_WiFiBtn2, -29);
    lv_obj_set_y(ui_WiFiBtn2, -62);
    lv_obj_set_align(ui_WiFiBtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn2, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName2 = lv_label_create(ui_WiFiBtn2);
    lv_obj_set_width(ui_WifiName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName2, "SSID2");
    lv_obj_set_style_text_font(ui_WifiName2, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn3 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn3, 151);
    lv_obj_set_height(ui_WiFiBtn3, 23);
    lv_obj_set_x(ui_WiFiBtn3, -29);
    lv_obj_set_y(ui_WiFiBtn3, -37);
    lv_obj_set_align(ui_WiFiBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn3, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName3 = lv_label_create(ui_WiFiBtn3);
    lv_obj_set_width(ui_WifiName3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName3, "SSID3");
    lv_obj_set_style_text_font(ui_WifiName3, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn4 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn4, 151);
    lv_obj_set_height(ui_WiFiBtn4, 23);
    lv_obj_set_x(ui_WiFiBtn4, -29);
    lv_obj_set_y(ui_WiFiBtn4, -12);
    lv_obj_set_align(ui_WiFiBtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn4, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName4 = lv_label_create(ui_WiFiBtn4);
    lv_obj_set_width(ui_WifiName4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName4, "SSID4");
    lv_obj_set_style_text_font(ui_WifiName4, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn5 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn5, 151);
    lv_obj_set_height(ui_WiFiBtn5, 23);
    lv_obj_set_x(ui_WiFiBtn5, -29);
    lv_obj_set_y(ui_WiFiBtn5, 13);
    lv_obj_set_align(ui_WiFiBtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn5, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName5 = lv_label_create(ui_WiFiBtn5);
    lv_obj_set_width(ui_WifiName5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName5, "SSID5");
    lv_obj_set_style_text_font(ui_WifiName5, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn6 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn6, 151);
    lv_obj_set_height(ui_WiFiBtn6, 23);
    lv_obj_set_x(ui_WiFiBtn6, -29);
    lv_obj_set_y(ui_WiFiBtn6, 38);
    lv_obj_set_align(ui_WiFiBtn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn6, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName6 = lv_label_create(ui_WiFiBtn6);
    lv_obj_set_width(ui_WifiName6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName6, "SSID6");
    lv_obj_set_style_text_font(ui_WifiName6, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn7 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn7, 151);
    lv_obj_set_height(ui_WiFiBtn7, 23);
    lv_obj_set_x(ui_WiFiBtn7, -29);
    lv_obj_set_y(ui_WiFiBtn7, 63);
    lv_obj_set_align(ui_WiFiBtn7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn7, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName7 = lv_label_create(ui_WiFiBtn7);
    lv_obj_set_width(ui_WifiName7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName7, "SSID7");
    lv_obj_set_style_text_font(ui_WifiName7, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn8 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn8, 151);
    lv_obj_set_height(ui_WiFiBtn8, 23);
    lv_obj_set_x(ui_WiFiBtn8, -29);
    lv_obj_set_y(ui_WiFiBtn8, 88);
    lv_obj_set_align(ui_WiFiBtn8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn8, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName8 = lv_label_create(ui_WiFiBtn8);
    lv_obj_set_width(ui_WifiName8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName8, "SSID8");
    lv_obj_set_style_text_font(ui_WifiName8, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn9 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn9, 151);
    lv_obj_set_height(ui_WiFiBtn9, 23);
    lv_obj_set_x(ui_WiFiBtn9, -29);
    lv_obj_set_y(ui_WiFiBtn9, 113);
    lv_obj_set_align(ui_WiFiBtn9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn9, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName9 = lv_label_create(ui_WiFiBtn9);
    lv_obj_set_width(ui_WifiName9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName9, "SSID9");
    lv_obj_set_style_text_font(ui_WifiName9, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiBtn10 = lv_btn_create(ui_SelectWifi);
    lv_obj_set_width(ui_WiFiBtn10, 151);
    lv_obj_set_height(ui_WiFiBtn10, 23);
    lv_obj_set_x(ui_WiFiBtn10, -29);
    lv_obj_set_y(ui_WiFiBtn10, 138);
    lv_obj_set_align(ui_WiFiBtn10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WiFiBtn10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WiFiBtn10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WiFiBtn10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WiFiBtn10, lv_color_hex(0x5E5E5E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WiFiBtn10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiName10 = lv_label_create(ui_WiFiBtn10);
    lv_obj_set_width(ui_WifiName10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiName10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiName10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiName10, "SSID10");
    lv_obj_set_style_text_font(ui_WifiName10, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiTopBar2 = lv_obj_create(ui_SelectWifi);
    lv_obj_set_width(ui_WifiTopBar2, 240);
    lv_obj_set_height(ui_WifiTopBar2, 49);
    lv_obj_set_x(ui_WifiTopBar2, 0);
    lv_obj_set_y(ui_WifiTopBar2, -136);
    lv_obj_set_align(ui_WifiTopBar2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiTopBar2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiTopBar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiTopBar2, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiTopBar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiTopBar2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_WifiTopBar2);
    lv_obj_set_width(ui_Button1, 29);
    lv_obj_set_height(ui_Button1, 33);
    lv_obj_set_x(ui_Button1, -94);
    lv_obj_set_y(ui_Button1, 0);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "<");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_SFPROEN_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SelectWIFIText = lv_label_create(ui_WifiTopBar2);
    lv_obj_set_width(ui_SelectWIFIText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SelectWIFIText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SelectWIFIText, 34);
    lv_obj_set_y(ui_SelectWIFIText, 2);
    lv_obj_set_align(ui_SelectWIFIText, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SelectWIFIText, "Select Wi-Fi (only for 2.4G)");
    lv_obj_set_style_text_align(ui_SelectWIFIText, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SelectWIFIText, &ui_font_SFPROEN_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiScancontain = lv_obj_create(ui_SelectWifi);
    lv_obj_remove_style_all(ui_WifiScancontain);
    lv_obj_set_width(ui_WifiScancontain, 240);
    lv_obj_set_height(ui_WifiScancontain, 320);
    lv_obj_set_align(ui_WifiScancontain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiScancontain, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_WifiScancontain, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiBlurPanel1 = lv_obj_create(ui_WifiScancontain);
    lv_obj_set_width(ui_WifiBlurPanel1, 240);
    lv_obj_set_height(ui_WifiBlurPanel1, 320);
    lv_obj_set_align(ui_WifiBlurPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiBlurPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiBlurPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiBlurPanel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiBlurPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiBlurPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_WifiBlurPanel1, 1500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPanel1 = lv_obj_create(ui_WifiScancontain);
    lv_obj_set_width(ui_WifiPanel1, 221);
    lv_obj_set_height(ui_WifiPanel1, 147);
    lv_obj_set_align(ui_WifiPanel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiPanel1, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiPanel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WifiPanel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiScanText = lv_label_create(ui_WifiPanel1);
    lv_obj_set_width(ui_WifiScanText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiScanText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiScanText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiScanText, "กำลังค้นหา...");
    lv_obj_set_style_text_font(ui_WifiScanText, &ui_font_THNEW_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_SelectWifi_screen_destroy(void)
{
    if(ui_SelectWifi) lv_obj_del(ui_SelectWifi);

    // NULL screen variables
    ui_SelectWifi = NULL;
    ui_RefreshWifiBtn = NULL;
    ui_Image7 = NULL;
    ui_WiFiBtn1 = NULL;
    ui_WifiName1 = NULL;
    ui_WiFiBtn2 = NULL;
    ui_WifiName2 = NULL;
    ui_WiFiBtn3 = NULL;
    ui_WifiName3 = NULL;
    ui_WiFiBtn4 = NULL;
    ui_WifiName4 = NULL;
    ui_WiFiBtn5 = NULL;
    ui_WifiName5 = NULL;
    ui_WiFiBtn6 = NULL;
    ui_WifiName6 = NULL;
    ui_WiFiBtn7 = NULL;
    ui_WifiName7 = NULL;
    ui_WiFiBtn8 = NULL;
    ui_WifiName8 = NULL;
    ui_WiFiBtn9 = NULL;
    ui_WifiName9 = NULL;
    ui_WiFiBtn10 = NULL;
    ui_WifiName10 = NULL;
    ui_WifiTopBar2 = NULL;
    ui_Button1 = NULL;
    ui_Label8 = NULL;
    ui_SelectWIFIText = NULL;
    ui_WifiScancontain = NULL;
    ui_WifiBlurPanel1 = NULL;
    ui_WifiPanel1 = NULL;
    ui_WifiScanText = NULL;

}
