// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Smart = NULL;
lv_obj_t * ui_SmartTipText = NULL;
lv_obj_t * ui_SmartTopBar = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_SmartText = NULL;
lv_obj_t * ui_SmartTipText1 = NULL;
lv_obj_t * ui_Image8 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

// build funtions

void ui_Smart_screen_init(void)
{
    ui_Smart = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Smart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SmartTipText = lv_label_create(ui_Smart);
    lv_obj_set_width(ui_SmartTipText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartTipText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartTipText, 0);
    lv_obj_set_y(ui_SmartTipText, 88);
    lv_obj_set_align(ui_SmartTipText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartTipText,
                      "โปรดแสกนคิวอาร์โค้ด\nเพื่อติดตามผลหรือเข้าเว็บไซต์");
    lv_obj_set_style_text_align(ui_SmartTipText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SmartTipText, &ui_font_SFPROTH_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartTopBar = lv_obj_create(ui_Smart);
    lv_obj_set_width(ui_SmartTopBar, 240);
    lv_obj_set_height(ui_SmartTopBar, 49);
    lv_obj_set_x(ui_SmartTopBar, 0);
    lv_obj_set_y(ui_SmartTopBar, -136);
    lv_obj_set_align(ui_SmartTopBar, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SmartTopBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SmartTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SmartTopBar, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SmartTopBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_SmartTopBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_SmartTopBar);
    lv_obj_set_width(ui_Button4, 29);
    lv_obj_set_height(ui_Button4, 33);
    lv_obj_set_x(ui_Button4, -94);
    lv_obj_set_y(ui_Button4, 0);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "<");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_SFPROEN_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartText = lv_label_create(ui_SmartTopBar);
    lv_obj_set_width(ui_SmartText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartText, -4);
    lv_obj_set_y(ui_SmartText, 0);
    lv_obj_set_align(ui_SmartText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartText, "Smart Webpage");
    lv_obj_set_style_text_font(ui_SmartText, &ui_font_SFPROEN_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SmartTipText1 = lv_label_create(ui_Smart);
    lv_obj_set_width(ui_SmartTipText1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SmartTipText1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SmartTipText1, 0);
    lv_obj_set_y(ui_SmartTipText1, 135);
    lv_obj_set_align(ui_SmartTipText1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SmartTipText1, "ricesense.cloud/device/8HI9L70C");
    lv_obj_set_style_text_color(ui_SmartTipText1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SmartTipText1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SmartTipText1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SmartTipText1, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Smart);
    lv_img_set_src(ui_Image8, &ui_img_qr_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 143
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 142
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, -19);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_Smart_screen_destroy(void)
{
    if(ui_Smart) lv_obj_del(ui_Smart);

    // NULL screen variables
    ui_Smart = NULL;
    ui_SmartTipText = NULL;
    ui_SmartTopBar = NULL;
    ui_Button4 = NULL;
    ui_Label10 = NULL;
    ui_SmartText = NULL;
    ui_SmartTipText1 = NULL;
    ui_Image8 = NULL;

}
