// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SMART_H
#define UI_SMART_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Smart
extern void ui_Smart_screen_init(void);
extern void ui_Smart_screen_destroy(void);
extern lv_obj_t * ui_Smart;
extern lv_obj_t * ui_SmartTipText;
extern lv_obj_t * ui_SmartTopBar;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_SmartText;
extern lv_obj_t * ui_SmartTipText1;
extern lv_obj_t * ui_Image8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

