// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_COLOR_H
#define UI_COLOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Color
extern void ui_Color_screen_init(void);
extern void ui_Color_screen_destroy(void);
extern lv_obj_t * ui_Color;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_RGBBox;
extern lv_obj_t * ui_RColor;
extern lv_obj_t * ui_GColor;
extern lv_obj_t * ui_BColor;
extern lv_obj_t * ui_RValue;
extern lv_obj_t * ui_GValue;
extern lv_obj_t * ui_BValue;
extern lv_obj_t * ui_GroupLabel;
extern lv_obj_t * ui_GroupValue;
extern lv_obj_t * ui_ChlValue;
extern lv_obj_t * ui_ChlLabel;
extern lv_obj_t * ui_ColorSaveButton;
extern lv_obj_t * ui_SaveLabel;
extern void ui_event_ActivateButton(lv_event_t * e);
extern lv_obj_t * ui_ActivateButton;
extern lv_obj_t * ui_ActivateLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

