// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Color = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_RGBBox = NULL;
lv_obj_t * ui_RColor = NULL;
lv_obj_t * ui_GColor = NULL;
lv_obj_t * ui_BColor = NULL;
lv_obj_t * ui_RValue = NULL;
lv_obj_t * ui_GValue = NULL;
lv_obj_t * ui_BValue = NULL;
lv_obj_t * ui_GroupLabel = NULL;
lv_obj_t * ui_GroupValue = NULL;
lv_obj_t * ui_ChlValue = NULL;
lv_obj_t * ui_ChlLabel = NULL;
lv_obj_t * ui_ColorSaveButton = NULL;
lv_obj_t * ui_SaveLabel = NULL;
lv_obj_t * ui_ActivateButton = NULL;
lv_obj_t * ui_ActivateLabel = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

void ui_event_ActivateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ui_event_LockButton(e);
    }
}

// build funtions

void ui_Color_screen_init(void)
{
    ui_Color = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Color, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Color);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, -185);
    lv_obj_set_y(ui_Button1, -131);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Color);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_x(ui_Label1, -189);
    lv_obj_set_y(ui_Label1, -130);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "<<");

    ui_RGBBox = lv_obj_create(ui_Color);
    lv_obj_set_width(ui_RGBBox, 220);
    lv_obj_set_height(ui_RGBBox, 170);
    lv_obj_set_x(ui_RGBBox, -102);
    lv_obj_set_y(ui_RGBBox, -3);
    lv_obj_set_align(ui_RGBBox, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RGBBox, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RColor = lv_label_create(ui_Color);
    lv_obj_set_width(ui_RColor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RColor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RColor, -199);
    lv_obj_set_y(ui_RColor, 119);
    lv_obj_set_align(ui_RColor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RColor, "R");

    ui_GColor = lv_label_create(ui_Color);
    lv_obj_set_width(ui_GColor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GColor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GColor, -119);
    lv_obj_set_y(ui_GColor, 119);
    lv_obj_set_align(ui_GColor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GColor, "G");

    ui_BColor = lv_label_create(ui_Color);
    lv_obj_set_width(ui_BColor, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BColor, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BColor, -35);
    lv_obj_set_y(ui_BColor, 122);
    lv_obj_set_align(ui_BColor, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BColor, "B");

    ui_RValue = lv_label_create(ui_Color);
    lv_obj_set_width(ui_RValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RValue, -166);
    lv_obj_set_y(ui_RValue, 120);
    lv_obj_set_align(ui_RValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RValue, "NaN");

    ui_GValue = lv_label_create(ui_Color);
    lv_obj_set_width(ui_GValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GValue, -82);
    lv_obj_set_y(ui_GValue, 121);
    lv_obj_set_align(ui_GValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GValue, "NaN");

    ui_BValue = lv_label_create(ui_Color);
    lv_obj_set_width(ui_BValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BValue, -4);
    lv_obj_set_y(ui_BValue, 121);
    lv_obj_set_align(ui_BValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BValue, "NaN");

    ui_GroupLabel = lv_label_create(ui_Color);
    lv_obj_set_width(ui_GroupLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GroupLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GroupLabel, 72);
    lv_obj_set_y(ui_GroupLabel, -88);
    lv_obj_set_align(ui_GroupLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GroupLabel, "Group");

    ui_GroupValue = lv_label_create(ui_Color);
    lv_obj_set_width(ui_GroupValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GroupValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GroupValue, 126);
    lv_obj_set_y(ui_GroupValue, -88);
    lv_obj_set_align(ui_GroupValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GroupValue, "0");

    ui_ChlValue = lv_label_create(ui_Color);
    lv_obj_set_width(ui_ChlValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChlValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChlValue, 101);
    lv_obj_set_y(ui_ChlValue, 122);
    lv_obj_set_align(ui_ChlValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChlValue, "NaN");

    ui_ChlLabel = lv_label_create(ui_Color);
    lv_obj_set_width(ui_ChlLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ChlLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ChlLabel, 58);
    lv_obj_set_y(ui_ChlLabel, 122);
    lv_obj_set_align(ui_ChlLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ChlLabel, "Chl");

    ui_ColorSaveButton = lv_btn_create(ui_Color);
    lv_obj_set_width(ui_ColorSaveButton, 100);
    lv_obj_set_height(ui_ColorSaveButton, 50);
    lv_obj_set_x(ui_ColorSaveButton, 101);
    lv_obj_set_y(ui_ColorSaveButton, -12);
    lv_obj_set_align(ui_ColorSaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ColorSaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ColorSaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SaveLabel = lv_label_create(ui_ColorSaveButton);
    lv_obj_set_width(ui_SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabel, "Save");

    ui_ActivateButton = lv_btn_create(ui_Color);
    lv_obj_set_width(ui_ActivateButton, 100);
    lv_obj_set_height(ui_ActivateButton, 50);
    lv_obj_set_x(ui_ActivateButton, 101);
    lv_obj_set_y(ui_ActivateButton, 52);
    lv_obj_set_align(ui_ActivateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ActivateButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ActivateButton, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ActivateButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ActivateButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ActivateButton, lv_color_hex(0x3EFF00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ActivateButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_ActivateLabel = lv_label_create(ui_ActivateButton);
    lv_obj_set_width(ui_ActivateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActivateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActivateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActivateLabel, "Activate");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ActivateButton, ui_event_ActivateButton, LV_EVENT_ALL, NULL);

}

void ui_Color_screen_destroy(void)
{
    if(ui_Color) lv_obj_del(ui_Color);

    // NULL screen variables
    ui_Color = NULL;
    ui_Button1 = NULL;
    ui_Label1 = NULL;
    ui_RGBBox = NULL;
    ui_RColor = NULL;
    ui_GColor = NULL;
    ui_BColor = NULL;
    ui_RValue = NULL;
    ui_GValue = NULL;
    ui_BValue = NULL;
    ui_GroupLabel = NULL;
    ui_GroupValue = NULL;
    ui_ChlValue = NULL;
    ui_ChlLabel = NULL;
    ui_ColorSaveButton = NULL;
    ui_SaveLabel = NULL;
    ui_ActivateButton = NULL;
    ui_ActivateLabel = NULL;

}
