// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

void BtnMinus_event_handler(lv_event_t * e)
{
	// Your code here
}

void BtnPlus_event_handler(lv_event_t * e)
{
	// Your code here
}

void ui_event_LockButton(lv_event_t * e)
{
	// Your code here
}
