// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Gps = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_LatitudeLabel = NULL;
lv_obj_t * ui_LongitudeLabel = NULL;
lv_obj_t * ui_LatitudeValue = NULL;
lv_obj_t * ui_LongtitudeValue = NULL;
lv_obj_t * ui_Minusbutton = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Addbutton = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_GardenValue = NULL;
lv_obj_t * ui_GardenLabel = NULL;
lv_obj_t * ui_Point1SaveButton = NULL;
lv_obj_t * ui_Point1SaveLabel = NULL;
lv_obj_t * ui_Point2SaveButton = NULL;
lv_obj_t * ui_Point2SaveLabel = NULL;
lv_obj_t * ui_Point3SaveButton = NULL;
lv_obj_t * ui_Point3SaveLabel = NULL;
lv_obj_t * ui_Point4SaveButton = NULL;
lv_obj_t * ui_Point4SaveLabel = NULL;
// event funtions
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Menu, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Menu_screen_init);
    }
}

void ui_event_Minusbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BtnMinus_event_handler(e);
    }
}

void ui_event_Addbutton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BtnPlus_event_handler(e);
    }
}

// build funtions

void ui_Gps_screen_init(void)
{
    ui_Gps = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Gps, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, -185);
    lv_obj_set_y(ui_Button2, -131);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 4
    lv_obj_set_x(ui_Label2, -189);
    lv_obj_set_y(ui_Label2, -130);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "<<");

    ui_LatitudeLabel = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_LatitudeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatitudeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LatitudeLabel, -186);
    lv_obj_set_y(ui_LatitudeLabel, 60);
    lv_obj_set_align(ui_LatitudeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LatitudeLabel, "Latitude");

    ui_LongitudeLabel = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_LongitudeLabel, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_height(ui_LongitudeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LongitudeLabel, -178);
    lv_obj_set_y(ui_LongitudeLabel, 101);
    lv_obj_set_align(ui_LongitudeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LongitudeLabel, "Longitude");

    ui_LatitudeValue = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_LatitudeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LatitudeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LatitudeValue, 133);
    lv_obj_set_y(ui_LatitudeValue, 213);
    lv_label_set_text(ui_LatitudeValue, "0.00000000000000");

    ui_LongtitudeValue = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_LongtitudeValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LongtitudeValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LongtitudeValue, 133);
    lv_obj_set_y(ui_LongtitudeValue, 254);
    lv_label_set_text(ui_LongtitudeValue, "0.00000000000000");

    ui_Minusbutton = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Minusbutton, 33);
    lv_obj_set_height(ui_Minusbutton, 41);
    lv_obj_set_x(ui_Minusbutton, -186);
    lv_obj_set_y(ui_Minusbutton, -55);
    lv_obj_set_align(ui_Minusbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Minusbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Minusbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Minusbutton);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "<");

    ui_Addbutton = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Addbutton, 33);
    lv_obj_set_height(ui_Addbutton, 41);
    lv_obj_set_x(ui_Addbutton, -99);
    lv_obj_set_y(ui_Addbutton, -55);
    lv_obj_set_align(ui_Addbutton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Addbutton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Addbutton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Addbutton);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, ">");

    ui_GardenValue = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_GardenValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GardenValue, -143);
    lv_obj_set_y(ui_GardenValue, -53);
    lv_obj_set_align(ui_GardenValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenValue, "0");

    ui_GardenLabel = lv_label_create(ui_Gps);
    lv_obj_set_width(ui_GardenLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GardenLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GardenLabel, -146);
    lv_obj_set_y(ui_GardenLabel, -14);
    lv_obj_set_align(ui_GardenLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GardenLabel, "Garden");

    ui_Point1SaveButton = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Point1SaveButton, 100);
    lv_obj_set_height(ui_Point1SaveButton, 41);
    lv_obj_set_x(ui_Point1SaveButton, -3);
    lv_obj_set_y(ui_Point1SaveButton, -101);
    lv_obj_set_align(ui_Point1SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Point1SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Point1SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Point1SaveLabel = lv_label_create(ui_Point1SaveButton);
    lv_obj_set_width(ui_Point1SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Point1SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Point1SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Point1SaveLabel, "Point 1 Save");

    ui_Point2SaveButton = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Point2SaveButton, 100);
    lv_obj_set_height(ui_Point2SaveButton, 41);
    lv_obj_set_x(ui_Point2SaveButton, 114);
    lv_obj_set_y(ui_Point2SaveButton, -99);
    lv_obj_set_align(ui_Point2SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Point2SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Point2SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Point2SaveLabel = lv_label_create(ui_Point2SaveButton);
    lv_obj_set_width(ui_Point2SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Point2SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Point2SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Point2SaveLabel, "Point 2 Save");

    ui_Point3SaveButton = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Point3SaveButton, 100);
    lv_obj_set_height(ui_Point3SaveButton, 41);
    lv_obj_set_x(ui_Point3SaveButton, -2);
    lv_obj_set_y(ui_Point3SaveButton, -42);
    lv_obj_set_align(ui_Point3SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Point3SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Point3SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Point3SaveLabel = lv_label_create(ui_Point3SaveButton);
    lv_obj_set_width(ui_Point3SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Point3SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Point3SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Point3SaveLabel, "Point 3 Save");

    ui_Point4SaveButton = lv_btn_create(ui_Gps);
    lv_obj_set_width(ui_Point4SaveButton, 100);
    lv_obj_set_height(ui_Point4SaveButton, 41);
    lv_obj_set_x(ui_Point4SaveButton, 113);
    lv_obj_set_y(ui_Point4SaveButton, -42);
    lv_obj_set_align(ui_Point4SaveButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Point4SaveButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Point4SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Point4SaveLabel = lv_label_create(ui_Point4SaveButton);
    lv_obj_set_width(ui_Point4SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Point4SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Point4SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Point4SaveLabel, "Point 4 Save");

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Minusbutton, ui_event_Minusbutton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Addbutton, ui_event_Addbutton, LV_EVENT_ALL, NULL);

}

void ui_Gps_screen_destroy(void)
{
    if(ui_Gps) lv_obj_del(ui_Gps);

    // NULL screen variables
    ui_Gps = NULL;
    ui_Button2 = NULL;
    ui_Label2 = NULL;
    ui_LatitudeLabel = NULL;
    ui_LongitudeLabel = NULL;
    ui_LatitudeValue = NULL;
    ui_LongtitudeValue = NULL;
    ui_Minusbutton = NULL;
    ui_Label12 = NULL;
    ui_Addbutton = NULL;
    ui_Label11 = NULL;
    ui_GardenValue = NULL;
    ui_GardenLabel = NULL;
    ui_Point1SaveButton = NULL;
    ui_Point1SaveLabel = NULL;
    ui_Point2SaveButton = NULL;
    ui_Point2SaveLabel = NULL;
    ui_Point3SaveButton = NULL;
    ui_Point3SaveLabel = NULL;
    ui_Point4SaveButton = NULL;
    ui_Point4SaveLabel = NULL;

}
