// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_GPS_H
#define UI_GPS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Gps
extern void ui_Gps_screen_init(void);
extern void ui_Gps_screen_destroy(void);
extern lv_obj_t * ui_Gps;
extern void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_LatitudeLabel;
extern lv_obj_t * ui_LongitudeLabel;
extern lv_obj_t * ui_LatitudeValue;
extern lv_obj_t * ui_LongtitudeValue;
extern void ui_event_Minusbutton(lv_event_t * e);
extern lv_obj_t * ui_Minusbutton;
extern lv_obj_t * ui_Label12;
extern void ui_event_Addbutton(lv_event_t * e);
extern lv_obj_t * ui_Addbutton;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_GardenValue;
extern lv_obj_t * ui_GardenLabel;
extern lv_obj_t * ui_Point1SaveButton;
extern lv_obj_t * ui_Point1SaveLabel;
extern lv_obj_t * ui_Point2SaveButton;
extern lv_obj_t * ui_Point2SaveLabel;
extern lv_obj_t * ui_Point3SaveButton;
extern lv_obj_t * ui_Point3SaveLabel;
extern lv_obj_t * ui_Point4SaveButton;
extern lv_obj_t * ui_Point4SaveLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

