// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_MENU_H
#define UI_MENU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Menu
extern void ui_Menu_screen_init(void);
extern void ui_Menu_screen_destroy(void);
extern lv_obj_t * ui_Menu;
extern void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

