// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#include "ui.h"

lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
// event funtions
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Color, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Color_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Wifi, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Wifi_screen_init);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Data, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Data_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Gps, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Gps_screen_init);
    }
}

// build funtions

void ui_Menu_screen_init(void)
{
    ui_Menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button5, 203);
    lv_obj_set_height(ui_Button5, 107);
    lv_obj_set_x(ui_Button5, -123);
    lv_obj_set_y(ui_Button5, -51);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button6 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button6, 203);
    lv_obj_set_height(ui_Button6, 107);
    lv_obj_set_x(ui_Button6, -124);
    lv_obj_set_y(ui_Button6, 80);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button7 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button7, 203);
    lv_obj_set_height(ui_Button7, 107);
    lv_obj_set_x(ui_Button7, 113);
    lv_obj_set_y(ui_Button7, 76);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_btn_create(ui_Menu);
    lv_obj_set_width(ui_Button8, 203);
    lv_obj_set_height(ui_Button8, 107);
    lv_obj_set_x(ui_Button8, 110);
    lv_obj_set_y(ui_Button8, -52);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -4);
    lv_obj_set_y(ui_Label5, -139);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "MENU");

    ui_Label6 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -132);
    lv_obj_set_y(ui_Label6, -51);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "COLOR");

    ui_Label7 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 110);
    lv_obj_set_y(ui_Label7, -53);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "GPS");

    ui_Label8 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, -130);
    lv_obj_set_y(ui_Label8, 80);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "WIFI");

    ui_Label9 = lv_label_create(ui_Menu);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 114);
    lv_obj_set_y(ui_Label9, 80);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "DATA");

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);

}

void ui_Menu_screen_destroy(void)
{
    if(ui_Menu) lv_obj_del(ui_Menu);

    // NULL screen variables
    ui_Menu = NULL;
    ui_Button5 = NULL;
    ui_Button6 = NULL;
    ui_Button7 = NULL;
    ui_Button8 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;

}
