// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: ui

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Wifi
extern void ui_Wifi_screen_init(void);
extern void ui_Wifi_screen_destroy(void);
extern lv_obj_t * ui_Wifi;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

